# Generated by Django 5.2.13 on 2026-04-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authauditevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authauditevent',
            new_name='accounts_au_event_t_587947_idx',
            old_name='accounts_au_event_t_852c86_idx',
        ),
        migrations.RenameIndex(
            model_name='authauditevent',
            new_name='accounts_au_status_abd7db_idx',
            old_name='accounts_au_status_3c97b4_idx',
        ),
    ]
