# Generated by Codex for access request workflow support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                (
                    "desired_role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("SUPERVISOR", "Supervisor"),
                            ("CHV", "CHV"),
                            ("ANALYST", "Analyst"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["review_status", "submitted_at"], name="accounts_ac_review__f8d357_idx"),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["contact_email", "submitted_at"], name="accounts_ac_contact_c29f00_idx"),
        ),
    ]
