# Generated by Django 5.2.13 on 2026-04-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_accessrequest_review_metadata"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accessrequest",
            new_name="accounts_ac_submitt_2337cb_idx",
            old_name="accounts_ac_ip_sub_idx",
        ),
    ]
