# Generated by Codex for TOTP recovery code foundation.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_accounts_ac_ip_sub_idx_accounts_ac_submitt_2337cb_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorRecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=255)),
                ("code_hint", models.CharField(blank=True, max_length=12)),
                ("batch_id", models.UUIDField(default=uuid.uuid4)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_recovery_codes",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "batch_id"], name="accounts_tw_user_id_68bb07_idx"),
                    models.Index(fields=["user", "used_at", "invalidated_at"], name="accounts_tw_user_id_65d96d_idx"),
                    models.Index(fields=["batch_id", "created_at"], name="accounts_tw_batch_i_3c961e_idx"),
                ],
            },
        ),
    ]
