# Generated by Codex for two-factor recovery-code audit events.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_twofactorrecoverycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("REFRESH_SUCCESS", "Refresh Success"),
                    ("REFRESH_FAILED", "Refresh Failed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("TWO_FACTOR_ENROLLMENT_REQUIRED", "Two-Factor Enrollment Required"),
                    ("TWO_FACTOR_ENROLLMENT_STARTED", "Two-Factor Enrollment Started"),
                    ("TWO_FACTOR_ENROLLMENT_COMPLETED", "Two-Factor Enrollment Completed"),
                    ("TWO_FACTOR_REQUIRED", "Two-Factor Required"),
                    ("TWO_FACTOR_VERIFIED", "Two-Factor Verified"),
                    ("TWO_FACTOR_FAILED", "Two-Factor Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_GENERATED", "Two-Factor Recovery Codes Generated"),
                    ("TWO_FACTOR_RECOVERY_CODES_REGENERATED", "Two-Factor Recovery Codes Regenerated"),
                    ("TWO_FACTOR_RECOVERY_CODE_USED", "Two-Factor Recovery Code Used"),
                    ("TWO_FACTOR_RECOVERY_CODE_FAILED", "Two-Factor Recovery Code Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_LOW", "Two-Factor Recovery Codes Low"),
                    ("USER_CREATED", "User Created"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_REACTIVATED", "User Reactivated"),
                ],
                max_length=40,
            ),
        ),
    ]
