# Generated by Codex for policy acceptance ledger.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_authauditevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPolicyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("TERMS", "Terms of Service"),
                            ("PRIVACY", "Privacy Policy"),
                            ("COOKIE_NOTICE", "Cookie Notice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("accepted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "acceptance_context",
                    models.CharField(
                        choices=[
                            ("first_sign_in", "First sign-in"),
                            ("version_update", "Version update"),
                            ("manual_review", "Manual review"),
                        ],
                        default="first_sign_in",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acceptances",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "document_type", "version"],
                        name="accounts_upa_user_doc_ver_idx",
                    ),
                    models.Index(
                        fields=["document_type", "version", "accepted_at"],
                        name="accounts_upa_doc_ver_at_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "document_type", "version"),
                        name="accounts_upa_user_doc_ver_uniq",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="authauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("REFRESH_SUCCESS", "Refresh Success"),
                    ("REFRESH_FAILED", "Refresh Failed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("TWO_FACTOR_ENROLLMENT_REQUIRED", "Two-Factor Enrollment Required"),
                    ("TWO_FACTOR_ENROLLMENT_STARTED", "Two-Factor Enrollment Started"),
                    ("TWO_FACTOR_ENROLLMENT_COMPLETED", "Two-Factor Enrollment Completed"),
                    ("TWO_FACTOR_REQUIRED", "Two-Factor Required"),
                    ("TWO_FACTOR_VERIFIED", "Two-Factor Verified"),
                    ("TWO_FACTOR_FAILED", "Two-Factor Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_GENERATED", "Two-Factor Recovery Codes Generated"),
                    ("TWO_FACTOR_RECOVERY_CODES_REGENERATED", "Two-Factor Recovery Codes Regenerated"),
                    ("TWO_FACTOR_RECOVERY_CODE_USED", "Two-Factor Recovery Code Used"),
                    ("TWO_FACTOR_RECOVERY_CODE_FAILED", "Two-Factor Recovery Code Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_LOW", "Two-Factor Recovery Codes Low"),
                    ("POLICY_ACCEPTANCE_REQUIRED", "Policy Acceptance Required"),
                    ("POLICY_ACCEPTED", "Policy Accepted"),
                    ("USER_CREATED", "User Created"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_REACTIVATED", "User Reactivated"),
                ],
                max_length=40,
            ),
        ),
    ]
