# Generated by Django 5.2.13 on 2026-05-07 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_policy_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REFRESH_SUCCESS', 'Refresh Success'), ('REFRESH_FAILED', 'Refresh Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('TWO_FACTOR_ENROLLMENT_REQUIRED', 'Two-Factor Enrollment Required'), ('TWO_FACTOR_ENROLLMENT_STARTED', 'Two-Factor Enrollment Started'), ('TWO_FACTOR_ENROLLMENT_COMPLETED', 'Two-Factor Enrollment Completed'), ('TWO_FACTOR_REQUIRED', 'Two-Factor Required'), ('TWO_FACTOR_VERIFIED', 'Two-Factor Verified'), ('TWO_FACTOR_FAILED', 'Two-Factor Failed'), ('TWO_FACTOR_RECOVERY_CODES_GENERATED', 'Two-Factor Recovery Codes Generated'), ('TWO_FACTOR_RECOVERY_CODES_REGENERATED', 'Two-Factor Recovery Codes Regenerated'), ('TWO_FACTOR_RECOVERY_CODE_USED', 'Two-Factor Recovery Code Used'), ('TWO_FACTOR_RECOVERY_CODE_FAILED', 'Two-Factor Recovery Code Failed'), ('TWO_FACTOR_RECOVERY_CODES_LOW', 'Two-Factor Recovery Codes Low'), ('POLICY_ACCEPTANCE_REQUIRED', 'Policy Acceptance Required'), ('POLICY_ACCEPTED', 'Policy Accepted'), ('USER_CREATED', 'User Created'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_REACTIVATED', 'User Reactivated'), ('SESSION_CREATED', 'Session Created'), ('SESSION_REFRESHED', 'Session Refreshed'), ('SESSION_REVOKED', 'Session Revoked'), ('SESSION_REPLAY_DETECTED', 'Session Replay Detected'), ('SESSION_CONTEXT_CHANGED', 'Session Context Changed'), ('STEP_UP_REQUIRED', 'Step-Up Required'), ('STEP_UP_VERIFIED', 'Step-Up Verified'), ('STEP_UP_FAILED', 'Step-Up Failed')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_family_id', models.UUIDField(default=uuid.uuid4)),
                ('current_refresh_jti_hash', models.CharField(max_length=64)),
                ('previous_refresh_jti_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_refresh_grace_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=120)),
                ('created_ip_prefix_hash', models.CharField(blank=True, max_length=64)),
                ('last_ip_prefix_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_label', models.CharField(blank=True, max_length=255)),
                ('device_label', models.CharField(blank=True, max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reason', models.TextField(blank=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_auth_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='accounts_us_user_id_e2902d_idx'), models.Index(fields=['public_id'], name='accounts_us_public__3dfcea_idx'), models.Index(fields=['token_family_id'], name='accounts_us_token_f_d8ebef_idx'), models.Index(fields=['current_refresh_jti_hash'], name='accounts_us_current_ff37c2_idx'), models.Index(fields=['previous_refresh_jti_hash'], name='accounts_us_previou_a895a2_idx'), models.Index(fields=['last_seen_at'], name='accounts_us_last_se_d9f804_idx')],
            },
        ),
    ]
