# Generated by Django 5.2.13 on 2026-05-08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_session_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepUpGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("admin_actions", "Admin actions"),
                            ("security_admin", "Security administration"),
                            ("system_controls", "System controls"),
                            ("sensitive_exports", "Sensitive exports"),
                            ("sensitive_export_download", "Sensitive export download"),
                            ("source_data", "Source data operations"),
                            ("message_governance", "Message governance"),
                            ("alert_delivery", "Alert delivery"),
                            ("operational_data", "Operational data"),
                        ],
                        max_length=40,
                    ),
                ),
                ("verified_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP"),
                            ("recovery_code", "Recovery code"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ip_prefix_hash", models.CharField(blank=True, max_length=64)),
                ("user_agent_hash", models.CharField(blank=True, max_length=64)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_up_grants",
                        to="accounts.usersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_up_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "session", "purpose", "expires_at"],
                        name="accounts_st_user_id_5b1a04_idx",
                    ),
                    models.Index(fields=["public_id"], name="accounts_st_public__e4753d_idx"),
                    models.Index(fields=["expires_at"], name="accounts_st_expires_073241_idx"),
                ],
            },
        ),
    ]
