# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_step_up_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("REFRESH_SUCCESS", "Refresh Success"),
                    ("REFRESH_FAILED", "Refresh Failed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("TWO_FACTOR_ENROLLMENT_REQUIRED", "Two-Factor Enrollment Required"),
                    ("TWO_FACTOR_ENROLLMENT_STARTED", "Two-Factor Enrollment Started"),
                    ("TWO_FACTOR_ENROLLMENT_COMPLETED", "Two-Factor Enrollment Completed"),
                    ("TWO_FACTOR_REQUIRED", "Two-Factor Required"),
                    ("TWO_FACTOR_VERIFIED", "Two-Factor Verified"),
                    ("TWO_FACTOR_FAILED", "Two-Factor Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_GENERATED", "Two-Factor Recovery Codes Generated"),
                    ("TWO_FACTOR_RECOVERY_CODES_REGENERATED", "Two-Factor Recovery Codes Regenerated"),
                    ("TWO_FACTOR_RECOVERY_CODE_USED", "Two-Factor Recovery Code Used"),
                    ("TWO_FACTOR_RECOVERY_CODE_FAILED", "Two-Factor Recovery Code Failed"),
                    ("TWO_FACTOR_RECOVERY_CODES_LOW", "Two-Factor Recovery Codes Low"),
                    ("POLICY_ACCEPTANCE_REQUIRED", "Policy Acceptance Required"),
                    ("POLICY_ACCEPTED", "Policy Accepted"),
                    ("USER_CREATED", "User Created"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_REACTIVATED", "User Reactivated"),
                    ("SESSION_CREATED", "Session Created"),
                    ("SESSION_REFRESHED", "Session Refreshed"),
                    ("SESSION_REVOKED", "Session Revoked"),
                    ("SESSION_REPLAY_DETECTED", "Session Replay Detected"),
                    ("SESSION_CONTEXT_CHANGED", "Session Context Changed"),
                    ("STEP_UP_REQUIRED", "Step-Up Required"),
                    ("STEP_UP_VERIFIED", "Step-Up Verified"),
                    ("STEP_UP_FAILED", "Step-Up Failed"),
                    ("HIGH_RISK_ACTION_COMPLETED", "High-Risk Action Completed"),
                ],
                max_length=40,
            ),
        ),
    ]
