from django.urls import path
from .views import (
    AlertIntelligenceAPIView,
    AlertWorkflowListAPIView,
    AlertDetailAPIView,
    AlertListAPIView,
    CHVAssignmentCancelAPIView,
    CHVAssignmentCompleteAPIView,
    CHVOperationsAPIView,
    CHVActivityAPIView,
    CHVMessageListCreateAPIView,
    CHVCoverageRequestApproveAPIView,
    CHVCoverageRequestAssignAPIView,
    CHVCoverageRequestCancelAPIView,
    CHVCoverageRequestDetailAPIView,
    CHVCoverageRequestFromAlertPrefillAPIView,
    CHVCoverageRequestListCreateAPIView,
    CHVCoverageRequestRejectAPIView,
    CHVCoverageRequestResolveAPIView,
    CHVListAPIView,
    CHVSyncAPIView,
    CHVTriageAPIView,
    HealthFacilityDetailAPIView,
    HealthFacilityForecastPreviewAPIView,
    HealthFacilityIntelligenceAPIView,
    HealthFacilityListAPIView,
    FacilityReadinessEscalationCreateAPIView,
    FacilityReadinessEscalationDetailAPIView,
    FacilityReadinessEscalationListAPIView,
    FacilityReadinessReviewAcknowledgeAPIView,
    FacilityReadinessReviewCreateAPIView,
    FacilityReadinessReviewDetailAPIView,
    FacilityReadinessReviewListAPIView,
    FacilityReadinessUpdateRequestCreateAPIView,
    IngestionRunListAPIView,
    LatestWardRiskAPIView,
    MigoriWardMapAPIView,
    FacilityForecastingStatusAPIView,
    FacilityForecastingEvaluationAPIView,
    ModelAlignmentAPIView,
    ModelRunListAPIView,
    DashboardNotificationAcknowledgeAPIView,
    DashboardNotificationDetailAPIView,
    DashboardNotificationDismissAPIView,
    DashboardNotificationListAPIView,
    DashboardNotificationMarkAllSeenAPIView,
    DashboardNotificationSeenAPIView,
    DashboardNotificationStreamTokenAPIView,
    RiskScoreListAPIView,
    ScenarioSimulationRunAPIView,
    TriggerAlertContextAPIView,
    TriggerAlertPreviewAPIView,
    TriggerAlertRequestStatusAPIView,
    TriggerAlertsAPIView,
    USSDMenuAPIView,
    UssdSessionLogListAPIView,
    WardDetailAPIView,
    WardIntelligenceAPIView,
    WardListAPIView,
)

urlpatterns = [
    path("wards/", WardListAPIView.as_view(), name="ward-list"),
    path("wards/<int:pk>/", WardDetailAPIView.as_view(), name="ward-detail"),
    path("wards/<int:pk>/intelligence/", WardIntelligenceAPIView.as_view(), name="ward-intelligence"),
    path("chvs/", CHVListAPIView.as_view(), name="chv-list"),
    path("chvs/operations/", CHVOperationsAPIView.as_view(), name="chv-operations"),
    path("chvs/<uuid:public_id>/activity/", CHVActivityAPIView.as_view(), name="chv-activity"),
    path("chvs/<uuid:public_id>/messages/", CHVMessageListCreateAPIView.as_view(), name="chv-message-list-create"),
    path("chv/coverage-requests/", CHVCoverageRequestListCreateAPIView.as_view(), name="chv-coverage-request-list-create"),
    path("chv/coverage-requests/from-alert/prefill/", CHVCoverageRequestFromAlertPrefillAPIView.as_view(), name="chv-coverage-request-from-alert-prefill"),
    path("chv/coverage-requests/<uuid:public_id>/", CHVCoverageRequestDetailAPIView.as_view(), name="chv-coverage-request-detail"),
    path("chv/coverage-requests/<uuid:public_id>/approve/", CHVCoverageRequestApproveAPIView.as_view(), name="chv-coverage-request-approve"),
    path("chv/coverage-requests/<uuid:public_id>/reject/", CHVCoverageRequestRejectAPIView.as_view(), name="chv-coverage-request-reject"),
    path("chv/coverage-requests/<uuid:public_id>/cancel/", CHVCoverageRequestCancelAPIView.as_view(), name="chv-coverage-request-cancel"),
    path("chv/coverage-requests/<uuid:public_id>/resolve/", CHVCoverageRequestResolveAPIView.as_view(), name="chv-coverage-request-resolve"),
    path("chv/coverage-requests/<uuid:public_id>/assign/", CHVCoverageRequestAssignAPIView.as_view(), name="chv-coverage-request-assign"),
    path("chv/assignments/<uuid:public_id>/complete/", CHVAssignmentCompleteAPIView.as_view(), name="chv-assignment-complete"),
    path("chv/assignments/<uuid:public_id>/cancel/", CHVAssignmentCancelAPIView.as_view(), name="chv-assignment-cancel"),
    path("ingestion-runs/", IngestionRunListAPIView.as_view(), name="ingestion-run-list"),
    path("model-runs/", ModelRunListAPIView.as_view(), name="model-run-list"),
    path("facilities/", HealthFacilityListAPIView.as_view(), name="facility-list"),
    path("facilities/<int:pk>/", HealthFacilityDetailAPIView.as_view(), name="facility-detail"),
    path("facilities/<int:pk>/intelligence/", HealthFacilityIntelligenceAPIView.as_view(), name="facility-intelligence"),
    path("facilities/<int:pk>/forecast-preview/", HealthFacilityForecastPreviewAPIView.as_view(), name="facility-forecast-preview"),
    path("facilities/<int:pk>/readiness-reviews/", FacilityReadinessReviewCreateAPIView.as_view(), name="facility-readiness-review-create"),
    path("facility-readiness/reviews/", FacilityReadinessReviewListAPIView.as_view(), name="facility-readiness-review-list"),
    path("facility-readiness/reviews/<uuid:public_id>/", FacilityReadinessReviewDetailAPIView.as_view(), name="facility-readiness-review-detail"),
    path("facility-readiness/reviews/<uuid:public_id>/acknowledge/", FacilityReadinessReviewAcknowledgeAPIView.as_view(), name="facility-readiness-review-acknowledge"),
    path("facility-readiness/reviews/<uuid:public_id>/update-requests/", FacilityReadinessUpdateRequestCreateAPIView.as_view(), name="facility-readiness-update-request-create"),
    path("facility-readiness/reviews/<uuid:public_id>/escalations/", FacilityReadinessEscalationCreateAPIView.as_view(), name="facility-readiness-escalation-create"),
    path("facility-readiness/escalations/", FacilityReadinessEscalationListAPIView.as_view(), name="facility-readiness-escalation-list"),
    path("facility-readiness/escalations/<uuid:public_id>/", FacilityReadinessEscalationDetailAPIView.as_view(), name="facility-readiness-escalation-detail"),
    path("facility-forecasting/status/", FacilityForecastingStatusAPIView.as_view(), name="facility-forecasting-status"),
    path("facility-forecasting/evaluation/", FacilityForecastingEvaluationAPIView.as_view(), name="facility-forecasting-evaluation"),
    path("risk-scores/", RiskScoreListAPIView.as_view(), name="risk-score-list"),
    path("risk-score/latest/", LatestWardRiskAPIView.as_view(), name="latest-ward-risk"),
    path("maps/wards/", MigoriWardMapAPIView.as_view(), name="migori-ward-map"),
    path("model-alignment/", ModelAlignmentAPIView.as_view(), name="model-alignment"),
    path("alerts/", AlertListAPIView.as_view(), name="alert-list"),
    path("alerts/<int:pk>/", AlertDetailAPIView.as_view(), name="alert-detail"),
    path("alerts/<int:pk>/intelligence/", AlertIntelligenceAPIView.as_view(), name="alert-intelligence"),
    path("alerts/workflows/", AlertWorkflowListAPIView.as_view(), name="alert-workflow-list"),
    path("alerts/trigger/context/", TriggerAlertContextAPIView.as_view(), name="trigger-alert-context"),
    path("alerts/trigger/preview/", TriggerAlertPreviewAPIView.as_view(), name="trigger-alert-preview"),
    path("alerts/trigger/requests/<uuid:request_id>/", TriggerAlertRequestStatusAPIView.as_view(), name="trigger-alert-request-status"),
    path("alerts/trigger/", TriggerAlertsAPIView.as_view(), name="trigger-alerts"),
    path("dashboard-scenarios/run/", ScenarioSimulationRunAPIView.as_view(), name="scenario-simulation-run"),
    path("notifications/", DashboardNotificationListAPIView.as_view(), name="notification-list"),
    path("notifications/stream-token/", DashboardNotificationStreamTokenAPIView.as_view(), name="notification-stream-token"),
    path("notifications/mark-all-seen/", DashboardNotificationMarkAllSeenAPIView.as_view(), name="notification-mark-all-seen"),
    path("notifications/<uuid:public_id>/", DashboardNotificationDetailAPIView.as_view(), name="notification-detail"),
    path("notifications/<uuid:public_id>/seen/", DashboardNotificationSeenAPIView.as_view(), name="notification-seen"),
    path("notifications/<uuid:public_id>/acknowledge/", DashboardNotificationAcknowledgeAPIView.as_view(), name="notification-acknowledge"),
    path("notifications/<uuid:public_id>/dismiss/", DashboardNotificationDismissAPIView.as_view(), name="notification-dismiss"),
    path("chv/triage/", CHVTriageAPIView.as_view(), name="chv-triage"),
    path("chv/sync/", CHVSyncAPIView.as_view(), name="chv-sync"),
    path("ussd/menu/", USSDMenuAPIView.as_view(), name="ussd-menu"),
    path("ussd/logs/", UssdSessionLogListAPIView.as_view(), name="ussd-log-list"),
]
