from django.urls import path
from .views import (
    AlertIntelligenceAPIView,
    AlertWorkflowListAPIView,
    AlertWorkflowPreparednessActionCreateAPIView,
    AlertDetailAPIView,
    AlertListAPIView,
    AlertPreparednessActionCreateAPIView,
    CHVAssignmentCancelAPIView,
    CHVAssignmentCompleteAPIView,
    CHVOperationsAPIView,
    CHVActivityAPIView,
    CHVDeviceRegistrationAPIView,
    CHVMessageListCreateAPIView,
    CHVCoverageRequestApproveAPIView,
    CHVCoverageRequestAssignAPIView,
    CHVCoverageRequestCancelAPIView,
    CHVCoverageRequestDetailAPIView,
    CHVCoverageRequestFromAlertPrefillAPIView,
    CHVCoverageRequestListCreateAPIView,
    CHVCoverageRequestRejectAPIView,
    CHVCoverageRequestResolveAPIView,
    CHVCoverageRequestPreparednessActionCreateAPIView,
    CHVListAPIView,
    CHVOfflineContractAPIView,
    CHVOfflineMonitoringAPIView,
    CHVSyncAPIView,
    CHVTriageAPIView,
    ContactPreferenceListCreateAPIView,
    HealthFacilityDetailAPIView,
    HealthFacilityForecastPreviewAPIView,
    HealthFacilityIntelligenceAPIView,
    HealthFacilityListAPIView,
    FacilityReadinessEscalationCreateAPIView,
    FacilityReadinessEscalationDetailAPIView,
    FacilityReadinessEscalationListAPIView,
    FacilityReadinessEscalationPreparednessActionCreateAPIView,
    FacilityReadinessReviewAcknowledgeAPIView,
    FacilityReadinessReviewCreateAPIView,
    FacilityReadinessReviewDetailAPIView,
    FacilityReadinessReviewListAPIView,
    FacilityReadinessReviewPreparednessActionCreateAPIView,
    FacilityReadinessUpdateRequestCreateAPIView,
    IngestionRunListAPIView,
    InteroperabilityCSVTemplateFileAPIView,
    InteroperabilityDashboardAPIView,
    InteroperabilityExportPreviewAPIView,
    InteroperabilityOrgUnitMappingImportAPIView,
    InteroperabilityRunDetailAPIView,
    InteroperabilityRunErrorFileAPIView,
    InteroperabilityRunRetryAPIView,
    LatestWardRiskAPIView,
    MobitechDeliveryCallbackAPIView,
    MigoriWardMapAPIView,
    FacilityForecastingStatusAPIView,
    FacilityForecastingEvaluationAPIView,
    ModelAlignmentAPIView,
    ModelOperationsHealthAPIView,
    MessageGovernanceDashboardAPIView,
    MessageTemplateApprovalAPIView,
    MessageTemplateGovernanceDetailAPIView,
    UssdMenuVersionApprovalAPIView,
    OperationalKPIAuditAPIView,
    ModelRunListAPIView,
    OperationalKPIDashboardAPIView,
    OperationalKPIMEExportAPIView,
    DashboardNotificationAcknowledgeAPIView,
    DashboardNotificationDetailAPIView,
    DashboardNotificationDismissAPIView,
    DashboardNotificationListAPIView,
    DashboardNotificationMarkAllSeenAPIView,
    DashboardNotificationSeenAPIView,
    DashboardNotificationStreamTokenAPIView,
    PreparednessActionDetailAPIView,
    PreparednessActionListCreateAPIView,
    RiskScoreListAPIView,
    ScenarioSimulationRunAPIView,
    SensitiveExportApproveAPIView,
    SensitiveExportDownloadAPIView,
    SensitiveExportRejectAPIView,
    SensitiveExportRequestListCreateAPIView,
    SourceDataCSVTemplateFileAPIView,
    SourceDataConnectorRefreshAPIView,
    SourceDataConnectorRegistryAPIView,
    SourceDataFeedTypesAPIView,
    SourceDataFeedModeAPIView,
    SourceDataFreshnessAPIView,
    SourceDataOperationsAPIView,
    SourceDataOverviewAPIView,
    SourceDataUploadApprovalAPIView,
    SourceDataUploadCancelAPIView,
    SourceDataUploadConfirmAPIView,
    SourceDataUploadDetailAPIView,
    SourceDataUploadDownstreamActionsAPIView,
    SourceDataUploadErrorsFileAPIView,
    SourceDataUploadListCreateAPIView,
    SourceDataUploadValidateAPIView,
    SystemAlertDeliveryPauseAPIView,
    SystemControlStatusAPIView,
    SystemManualRiskScoringAPIView,
    SystemReadinessAPIView,
    SystemRetryControlsAPIView,
    TriggerAlertContextAPIView,
    TriggerAlertPreviewAPIView,
    TriggerAlertRequestStatusAPIView,
    TriggerAlertsAPIView,
    USSDMenuAPIView,
    UssdSessionLogListAPIView,
    WardDetailAPIView,
    WardIntelligenceAPIView,
    WardListAPIView,
)

urlpatterns = [
    path("sms/mobitech/callback/", MobitechDeliveryCallbackAPIView.as_view(), name="mobitech-delivery-callback"),
    path("wards/", WardListAPIView.as_view(), name="ward-list"),
    path("wards/<int:pk>/", WardDetailAPIView.as_view(), name="ward-detail"),
    path("wards/<int:pk>/intelligence/", WardIntelligenceAPIView.as_view(), name="ward-intelligence"),
    path("chvs/", CHVListAPIView.as_view(), name="chv-list"),
    path("chvs/operations/", CHVOperationsAPIView.as_view(), name="chv-operations"),
    path("chvs/<uuid:public_id>/activity/", CHVActivityAPIView.as_view(), name="chv-activity"),
    path("chvs/<uuid:public_id>/messages/", CHVMessageListCreateAPIView.as_view(), name="chv-message-list-create"),
    path("chv/offline/contract/", CHVOfflineContractAPIView.as_view(), name="chv-offline-contract"),
    path("chv/offline/monitoring/", CHVOfflineMonitoringAPIView.as_view(), name="chv-offline-monitoring"),
    path("chv/device-registrations/", CHVDeviceRegistrationAPIView.as_view(), name="chv-device-registration"),
    path("chv/coverage-requests/", CHVCoverageRequestListCreateAPIView.as_view(), name="chv-coverage-request-list-create"),
    path("chv/coverage-requests/from-alert/prefill/", CHVCoverageRequestFromAlertPrefillAPIView.as_view(), name="chv-coverage-request-from-alert-prefill"),
    path("chv/coverage-requests/<uuid:public_id>/", CHVCoverageRequestDetailAPIView.as_view(), name="chv-coverage-request-detail"),
    path("chv/coverage-requests/<uuid:public_id>/approve/", CHVCoverageRequestApproveAPIView.as_view(), name="chv-coverage-request-approve"),
    path("chv/coverage-requests/<uuid:public_id>/reject/", CHVCoverageRequestRejectAPIView.as_view(), name="chv-coverage-request-reject"),
    path("chv/coverage-requests/<uuid:public_id>/cancel/", CHVCoverageRequestCancelAPIView.as_view(), name="chv-coverage-request-cancel"),
    path("chv/coverage-requests/<uuid:public_id>/resolve/", CHVCoverageRequestResolveAPIView.as_view(), name="chv-coverage-request-resolve"),
    path("chv/coverage-requests/<uuid:public_id>/assign/", CHVCoverageRequestAssignAPIView.as_view(), name="chv-coverage-request-assign"),
    path("chv/coverage-requests/<uuid:public_id>/preparedness-actions/", CHVCoverageRequestPreparednessActionCreateAPIView.as_view(), name="chv-coverage-request-preparedness-action-create"),
    path("chv/assignments/<uuid:public_id>/complete/", CHVAssignmentCompleteAPIView.as_view(), name="chv-assignment-complete"),
    path("chv/assignments/<uuid:public_id>/cancel/", CHVAssignmentCancelAPIView.as_view(), name="chv-assignment-cancel"),
    path("contact-preferences/", ContactPreferenceListCreateAPIView.as_view(), name="contact-preference-list-create"),
    path("ingestion-runs/", IngestionRunListAPIView.as_view(), name="ingestion-run-list"),
    path("model-runs/", ModelRunListAPIView.as_view(), name="model-run-list"),
    path("facilities/", HealthFacilityListAPIView.as_view(), name="facility-list"),
    path("facilities/<int:pk>/", HealthFacilityDetailAPIView.as_view(), name="facility-detail"),
    path("facilities/<int:pk>/intelligence/", HealthFacilityIntelligenceAPIView.as_view(), name="facility-intelligence"),
    path("facilities/<int:pk>/forecast-preview/", HealthFacilityForecastPreviewAPIView.as_view(), name="facility-forecast-preview"),
    path("facilities/<int:pk>/readiness-reviews/", FacilityReadinessReviewCreateAPIView.as_view(), name="facility-readiness-review-create"),
    path("facility-readiness/reviews/", FacilityReadinessReviewListAPIView.as_view(), name="facility-readiness-review-list"),
    path("facility-readiness/reviews/<uuid:public_id>/", FacilityReadinessReviewDetailAPIView.as_view(), name="facility-readiness-review-detail"),
    path("facility-readiness/reviews/<uuid:public_id>/acknowledge/", FacilityReadinessReviewAcknowledgeAPIView.as_view(), name="facility-readiness-review-acknowledge"),
    path("facility-readiness/reviews/<uuid:public_id>/update-requests/", FacilityReadinessUpdateRequestCreateAPIView.as_view(), name="facility-readiness-update-request-create"),
    path("facility-readiness/reviews/<uuid:public_id>/escalations/", FacilityReadinessEscalationCreateAPIView.as_view(), name="facility-readiness-escalation-create"),
    path("facility-readiness/reviews/<uuid:public_id>/preparedness-actions/", FacilityReadinessReviewPreparednessActionCreateAPIView.as_view(), name="facility-readiness-review-preparedness-action-create"),
    path("facility-readiness/escalations/", FacilityReadinessEscalationListAPIView.as_view(), name="facility-readiness-escalation-list"),
    path("facility-readiness/escalations/<uuid:public_id>/", FacilityReadinessEscalationDetailAPIView.as_view(), name="facility-readiness-escalation-detail"),
    path("facility-readiness/escalations/<uuid:public_id>/preparedness-actions/", FacilityReadinessEscalationPreparednessActionCreateAPIView.as_view(), name="facility-readiness-escalation-preparedness-action-create"),
    path("facility-forecasting/status/", FacilityForecastingStatusAPIView.as_view(), name="facility-forecasting-status"),
    path("facility-forecasting/evaluation/", FacilityForecastingEvaluationAPIView.as_view(), name="facility-forecasting-evaluation"),
    path("risk-scores/", RiskScoreListAPIView.as_view(), name="risk-score-list"),
    path("risk-score/latest/", LatestWardRiskAPIView.as_view(), name="latest-ward-risk"),
    path("maps/wards/", MigoriWardMapAPIView.as_view(), name="migori-ward-map"),
    path("model-alignment/", ModelAlignmentAPIView.as_view(), name="model-alignment"),
    path("model-operations/health/", ModelOperationsHealthAPIView.as_view(), name="model-operations-health"),
    path("operational-metrics/dashboard/", OperationalKPIDashboardAPIView.as_view(), name="operational-kpi-dashboard"),
    path("operational-metrics/audit/", OperationalKPIAuditAPIView.as_view(), name="operational-kpi-audit"),
    path("operational-metrics/me-export/", OperationalKPIMEExportAPIView.as_view(), name="operational-kpi-me-export"),
    path("source-data/feed-types/", SourceDataFeedTypesAPIView.as_view(), name="source-data-feed-types"),
    path("source-data/overview/", SourceDataOverviewAPIView.as_view(), name="source-data-overview"),
    path("source-data/freshness/", SourceDataFreshnessAPIView.as_view(), name="source-data-freshness"),
    path("source-data/operations/", SourceDataOperationsAPIView.as_view(), name="source-data-operations"),
    path("source-data/connectors/", SourceDataConnectorRegistryAPIView.as_view(), name="source-data-connectors"),
    path("source-data/connectors/<str:connector_key>/refresh/", SourceDataConnectorRefreshAPIView.as_view(), name="source-data-connector-refresh"),
    path("source-data/feed-modes/<str:feed_key>/", SourceDataFeedModeAPIView.as_view(), name="source-data-feed-mode"),
    path("source-data/templates/<str:feed_key>/", SourceDataCSVTemplateFileAPIView.as_view(), name="source-data-template-file"),
    path("source-data/uploads/", SourceDataUploadListCreateAPIView.as_view(), name="source-data-upload-list-create"),
    path("source-data/uploads/<uuid:public_id>/", SourceDataUploadDetailAPIView.as_view(), name="source-data-upload-detail"),
    path("source-data/uploads/<uuid:public_id>/validate/", SourceDataUploadValidateAPIView.as_view(), name="source-data-upload-validate"),
    path("source-data/uploads/<uuid:public_id>/approval/", SourceDataUploadApprovalAPIView.as_view(), name="source-data-upload-approval"),
    path("source-data/uploads/<uuid:public_id>/confirm/", SourceDataUploadConfirmAPIView.as_view(), name="source-data-upload-confirm"),
    path("source-data/uploads/<uuid:public_id>/cancel/", SourceDataUploadCancelAPIView.as_view(), name="source-data-upload-cancel"),
    path("source-data/uploads/<uuid:public_id>/downstream-actions/", SourceDataUploadDownstreamActionsAPIView.as_view(), name="source-data-upload-downstream-actions"),
    path("source-data/uploads/<uuid:public_id>/errors.csv/", SourceDataUploadErrorsFileAPIView.as_view(), name="source-data-upload-errors-file"),
    path("interoperability/dashboard/", InteroperabilityDashboardAPIView.as_view(), name="interoperability-dashboard"),
    path("interoperability/csv-templates/<str:exchange_type>/", InteroperabilityCSVTemplateFileAPIView.as_view(), name="interoperability-csv-template-file"),
    path("interoperability/org-unit-mapping-imports/", InteroperabilityOrgUnitMappingImportAPIView.as_view(), name="interoperability-org-unit-mapping-import"),
    path("interoperability/export-previews/risk-scores/", InteroperabilityExportPreviewAPIView.as_view(), name="interoperability-risk-score-export-preview"),
    path("interoperability/runs/<uuid:public_id>/", InteroperabilityRunDetailAPIView.as_view(), name="interoperability-run-detail"),
    path("interoperability/runs/<uuid:public_id>/retry/", InteroperabilityRunRetryAPIView.as_view(), name="interoperability-run-retry"),
    path("interoperability/runs/<uuid:public_id>/errors.csv/", InteroperabilityRunErrorFileAPIView.as_view(), name="interoperability-run-error-file"),
    path("message-governance/dashboard/", MessageGovernanceDashboardAPIView.as_view(), name="message-governance-dashboard"),
    path("message-governance/templates/<uuid:public_id>/", MessageTemplateGovernanceDetailAPIView.as_view(), name="message-template-governance-detail"),
    path("message-governance/templates/<uuid:public_id>/approval/", MessageTemplateApprovalAPIView.as_view(), name="message-template-approval"),
    path("message-governance/ussd-menu-versions/<uuid:public_id>/approval/", UssdMenuVersionApprovalAPIView.as_view(), name="ussd-menu-version-approval"),
    path("system/readiness/", SystemReadinessAPIView.as_view(), name="system-readiness"),
    path("system/controls/", SystemControlStatusAPIView.as_view(), name="system-control-status"),
    path("system/controls/retry/", SystemRetryControlsAPIView.as_view(), name="system-control-retry"),
    path("system/controls/manual-risk-scoring/", SystemManualRiskScoringAPIView.as_view(), name="system-control-manual-risk-scoring"),
    path("system/controls/alert-delivery-pause/", SystemAlertDeliveryPauseAPIView.as_view(), name="system-control-alert-delivery-pause"),
    path("alerts/", AlertListAPIView.as_view(), name="alert-list"),
    path("alerts/<int:pk>/", AlertDetailAPIView.as_view(), name="alert-detail"),
    path("alerts/<int:pk>/intelligence/", AlertIntelligenceAPIView.as_view(), name="alert-intelligence"),
    path("alerts/<int:pk>/preparedness-actions/", AlertPreparednessActionCreateAPIView.as_view(), name="alert-preparedness-action-create"),
    path("sensitive-exports/", SensitiveExportRequestListCreateAPIView.as_view(), name="sensitive-export-list-create"),
    path("sensitive-exports/<uuid:public_id>/approve/", SensitiveExportApproveAPIView.as_view(), name="sensitive-export-approve"),
    path("sensitive-exports/<uuid:public_id>/reject/", SensitiveExportRejectAPIView.as_view(), name="sensitive-export-reject"),
    path("sensitive-exports/<uuid:public_id>/download/", SensitiveExportDownloadAPIView.as_view(), name="sensitive-export-download"),
    path("alerts/workflows/", AlertWorkflowListAPIView.as_view(), name="alert-workflow-list"),
    path("alerts/workflows/<uuid:public_id>/preparedness-actions/", AlertWorkflowPreparednessActionCreateAPIView.as_view(), name="alert-workflow-preparedness-action-create"),
    path("alerts/trigger/context/", TriggerAlertContextAPIView.as_view(), name="trigger-alert-context"),
    path("alerts/trigger/preview/", TriggerAlertPreviewAPIView.as_view(), name="trigger-alert-preview"),
    path("alerts/trigger/requests/<uuid:request_id>/", TriggerAlertRequestStatusAPIView.as_view(), name="trigger-alert-request-status"),
    path("alerts/trigger/", TriggerAlertsAPIView.as_view(), name="trigger-alerts"),
    path("preparedness-actions/", PreparednessActionListCreateAPIView.as_view(), name="preparedness-action-list-create"),
    path("preparedness-actions/<uuid:public_id>/", PreparednessActionDetailAPIView.as_view(), name="preparedness-action-detail"),
    path("dashboard-scenarios/run/", ScenarioSimulationRunAPIView.as_view(), name="scenario-simulation-run"),
    path("notifications/", DashboardNotificationListAPIView.as_view(), name="notification-list"),
    path("notifications/stream-token/", DashboardNotificationStreamTokenAPIView.as_view(), name="notification-stream-token"),
    path("notifications/mark-all-seen/", DashboardNotificationMarkAllSeenAPIView.as_view(), name="notification-mark-all-seen"),
    path("notifications/<uuid:public_id>/", DashboardNotificationDetailAPIView.as_view(), name="notification-detail"),
    path("notifications/<uuid:public_id>/seen/", DashboardNotificationSeenAPIView.as_view(), name="notification-seen"),
    path("notifications/<uuid:public_id>/acknowledge/", DashboardNotificationAcknowledgeAPIView.as_view(), name="notification-acknowledge"),
    path("notifications/<uuid:public_id>/dismiss/", DashboardNotificationDismissAPIView.as_view(), name="notification-dismiss"),
    path("chv/triage/", CHVTriageAPIView.as_view(), name="chv-triage"),
    path("chv/sync/", CHVSyncAPIView.as_view(), name="chv-sync"),
    path("ussd/menu/", USSDMenuAPIView.as_view(), name="ussd-menu"),
    path("ussd/logs/", UssdSessionLogListAPIView.as_view(), name="ussd-log-list"),
]
