from django.urls import path
from .views import (
    AlertIntelligenceAPIView,
    AlertDetailAPIView,
    AlertListAPIView,
    CHVOperationsAPIView,
    CHVListAPIView,
    CHVSyncAPIView,
    CHVTriageAPIView,
    HealthFacilityDetailAPIView,
    HealthFacilityListAPIView,
    LatestWardRiskAPIView,
    MigoriWardMapAPIView,
    RiskScoreListAPIView,
    TriggerAlertsAPIView,
    USSDMenuAPIView,
    UssdSessionLogListAPIView,
    WardDetailAPIView,
    WardIntelligenceAPIView,
    WardListAPIView,
)

urlpatterns = [
    path("wards/", WardListAPIView.as_view(), name="ward-list"),
    path("wards/<int:pk>/", WardDetailAPIView.as_view(), name="ward-detail"),
    path("wards/<int:pk>/intelligence/", WardIntelligenceAPIView.as_view(), name="ward-intelligence"),
    path("chvs/", CHVListAPIView.as_view(), name="chv-list"),
    path("chvs/operations/", CHVOperationsAPIView.as_view(), name="chv-operations"),
    path("facilities/", HealthFacilityListAPIView.as_view(), name="facility-list"),
    path("facilities/<int:pk>/", HealthFacilityDetailAPIView.as_view(), name="facility-detail"),
    path("risk-scores/", RiskScoreListAPIView.as_view(), name="risk-score-list"),
    path("risk-score/latest/", LatestWardRiskAPIView.as_view(), name="latest-ward-risk"),
    path("maps/wards/", MigoriWardMapAPIView.as_view(), name="migori-ward-map"),
    path("alerts/", AlertListAPIView.as_view(), name="alert-list"),
    path("alerts/<int:pk>/", AlertDetailAPIView.as_view(), name="alert-detail"),
    path("alerts/<int:pk>/intelligence/", AlertIntelligenceAPIView.as_view(), name="alert-intelligence"),
    path("alerts/trigger/", TriggerAlertsAPIView.as_view(), name="trigger-alerts"),
    path("chv/triage/", CHVTriageAPIView.as_view(), name="chv-triage"),
    path("chv/sync/", CHVSyncAPIView.as_view(), name="chv-sync"),
    path("ussd/menu/", USSDMenuAPIView.as_view(), name="ussd-menu"),
    path("ussd/logs/", UssdSessionLogListAPIView.as_view(), name="ussd-log-list"),
]
