import { describe, expect, it, vi } from "vitest";

import { GET } from "@/app/api/dashboard/wards/route";

const mockFetchBackendJson = vi.fn();

vi.mock("@/lib/server-api", () => ({
  ServerApiError: class ServerApiError extends Error {
    status: number;

    constructor(status: number, message: string) {
      super(message);
      this.status = status;
    }
  },
  fetchBackendJson: (...args: unknown[]) => mockFetchBackendJson(...args),
}));

describe("dashboard wards route", () => {
  it("merges workflow truth into ward queue items and summaries", async () => {
    mockFetchBackendJson
      .mockResolvedValueOnce({
        count: 2,
        next: null,
        previous: null,
        results: [
          {
            id: 1,
            public_id: "WRD-001",
            name: "North Kamagambo",
            county: "Migori",
            sub_county: "Rongo",
            ward_code: "MIG-01",
            current_risk_level: "LOW",
            current_risk_score: 0.1,
            is_active: true,
            updated_at: "2026-04-27T08:00:00Z",
          },
          {
            id: 2,
            public_id: "WRD-002",
            name: "South Kadem",
            county: "Migori",
            sub_county: "Nyatike",
            ward_code: "MIG-02",
            current_risk_level: "LOW",
            current_risk_score: 0.2,
            is_active: true,
            updated_at: "2026-04-27T09:00:00Z",
          },
        ],
      })
      .mockResolvedValueOnce([
        {
          ward_id: 1,
          ward_name: "North Kamagambo",
          risk_level: "MEDIUM",
          risk_score: 0.55,
          predicted_cases: 3,
          generated_at: "2026-04-27T10:00:00Z",
        },
      ])
      .mockResolvedValueOnce({
        count: 2,
        next: null,
        previous: null,
        results: [
          {
            id: 50,
            ward: 1,
            ward_name: "North Kamagambo",
            risk_score: 55,
            channel: "SMS",
            recipient: "254700000001",
            message: "Review ward",
            status: "RETRY_PENDING",
            delivery_backend: "sms",
            attempt_count: 1,
            max_attempts: 3,
            last_attempted_at: null,
            next_retry_at: null,
            external_id: "ext-1",
            sent_at: null,
            created_at: "2026-04-27T10:05:00Z",
            error_message: "",
          },
          {
            id: 51,
            ward: 1,
            ward_name: "North Kamagambo",
            risk_score: 55,
            channel: "DASHBOARD",
            recipient: "ops",
            message: "Review ward",
            status: "QUEUED",
            delivery_backend: "dashboard",
            attempt_count: 0,
            max_attempts: 1,
            last_attempted_at: null,
            next_retry_at: null,
            external_id: "ext-2",
            sent_at: null,
            created_at: "2026-04-27T10:06:00Z",
            error_message: "",
          },
        ],
      })
      .mockResolvedValueOnce({
        count: 3,
        results: [
          {
            id: 100,
            public_id: "WF-100",
            ward_id: 1,
            ward_name: "North Kamagambo",
            status: "REVIEW_PENDING",
            decision_mode: "rule" as const,
            confidence: "high" as const,
            trigger_severity: "high" as const,
            alert_delivery_state: "retry_pending" as const,
            alert_delivery_label: "Retry pending",
            risk_level: "HIGH",
            risk_score: 82,
            predicted_cases: 6,
            reason_flagged: "spike",
            trigger_reason: "Risk spike detected",
            recommended_action: "Review trigger and verify ward conditions",
            recommended_response: "Follow up",
            expected_operational_effect: "Raised monitoring",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 2,
            delivered_alert_count: 0,
            retry_pending_alert_count: 1,
            failed_alert_count: 0,
            queued_alert_count: 1,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:10:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:10:00Z",
          },
          {
            id: 101,
            public_id: "WF-101",
            ward_id: 1,
            ward_name: "North Kamagambo",
            status: "RESOLVED",
            decision_mode: "rule" as const,
            confidence: "review" as const,
            trigger_severity: "review" as const,
            alert_delivery_state: "delivered" as const,
            alert_delivery_label: "Delivered",
            risk_level: "LOW",
            risk_score: 10,
            predicted_cases: 1,
            reason_flagged: "old",
            trigger_reason: "Old workflow",
            recommended_action: "No action",
            recommended_response: "No action",
            expected_operational_effect: "None",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 0,
            delivered_alert_count: 1,
            retry_pending_alert_count: 0,
            failed_alert_count: 0,
            queued_alert_count: 0,
            triggered_at: null,
            latest_risk_update_at: "2026-04-26T10:10:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-26T10:10:00Z",
          },
          {
            id: 102,
            public_id: "WF-102",
            ward_id: 99,
            ward_name: "Outside Scope",
            status: "FAILED",
            decision_mode: "rule" as const,
            confidence: "high" as const,
            trigger_severity: "high" as const,
            alert_delivery_state: "failed" as const,
            alert_delivery_label: "Failed",
            risk_level: "HIGH",
            risk_score: 99,
            predicted_cases: 8,
            reason_flagged: "outside",
            trigger_reason: "Outside ward",
            recommended_action: "Ignore for this page",
            recommended_response: "Ignore",
            expected_operational_effect: "None",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 1,
            delivered_alert_count: 0,
            retry_pending_alert_count: 0,
            failed_alert_count: 1,
            queued_alert_count: 0,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:11:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:11:00Z",
          },
        ],
      });

    const request = new Request("http://localhost:3000/api/dashboard/wards?county=Migori");
    const response = await GET(request);
    const payload = await response.json();

    expect(response.status).toBe(200);
    expect(payload.wardQueue.items).toHaveLength(2);
    expect(payload.wardQueue.items[0]).toMatchObject({
      id: 1,
      trigger_state: "REVIEW_PENDING",
      requires_action: true,
      expected_cases_7d: 6,
      delivery_concern_count: 1,
      workflow_public_id: "WF-100",
      recommended_action: "Review trigger and verify ward conditions",
      recent_alert_count: 2,
    });
    expect(payload.wardQueue.items[1]).toMatchObject({
      id: 2,
      trigger_state: "NONE",
      requires_action: false,
      expected_cases_7d: null,
      delivery_concern_count: 0,
    });
    expect(payload.wardQueue.summary).toEqual({
      wards_requiring_action: 1,
      workflow_active_wards: 1,
      alerts_pending: 1,
    });
    expect(payload.wardQueue.urgency).toEqual({
      has_actionable_wards: true,
      requires_action_count: 1,
    });
  });

  it("normalizes raw workflow states into the shared page-level queue vocabulary", async () => {
    mockFetchBackendJson
      .mockResolvedValueOnce({
        count: 4,
        next: null,
        previous: null,
        results: [
          {
            id: 11,
            public_id: "WRD-011",
            name: "A",
            county: "Migori",
            sub_county: "Rongo",
            ward_code: "MIG-11",
            current_risk_level: "LOW",
            current_risk_score: 0.1,
            is_active: true,
            updated_at: "2026-04-27T08:00:00Z",
          },
          {
            id: 12,
            public_id: "WRD-012",
            name: "B",
            county: "Migori",
            sub_county: "Rongo",
            ward_code: "MIG-12",
            current_risk_level: "LOW",
            current_risk_score: 0.1,
            is_active: true,
            updated_at: "2026-04-27T08:00:00Z",
          },
          {
            id: 13,
            public_id: "WRD-013",
            name: "C",
            county: "Migori",
            sub_county: "Rongo",
            ward_code: "MIG-13",
            current_risk_level: "LOW",
            current_risk_score: 0.1,
            is_active: true,
            updated_at: "2026-04-27T08:00:00Z",
          },
          {
            id: 14,
            public_id: "WRD-014",
            name: "D",
            county: "Migori",
            sub_county: "Rongo",
            ward_code: "MIG-14",
            current_risk_level: "LOW",
            current_risk_score: 0.1,
            is_active: true,
            updated_at: "2026-04-27T08:00:00Z",
          },
        ],
      })
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce({
        count: 0,
        next: null,
        previous: null,
        results: [],
      })
      .mockResolvedValueOnce({
        count: 4,
        results: [
          {
            id: 201,
            public_id: "WF-201",
            ward_id: 11,
            ward_name: "A",
            status: "QUEUED",
            decision_mode: "rule" as const,
            confidence: "high" as const,
            trigger_severity: "high" as const,
            alert_delivery_state: "queued" as const,
            alert_delivery_label: "Queued",
            risk_level: "HIGH",
            risk_score: 90,
            predicted_cases: 10,
            reason_flagged: "queue",
            trigger_reason: "Queued workflow",
            recommended_action: "Watch queue",
            recommended_response: "Watch queue",
            expected_operational_effect: "Queued",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 1,
            delivered_alert_count: 0,
            retry_pending_alert_count: 0,
            failed_alert_count: 0,
            queued_alert_count: 1,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:10:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:10:00Z",
          },
          {
            id: 202,
            public_id: "WF-202",
            ward_id: 12,
            ward_name: "B",
            status: "FAILED",
            decision_mode: "rule" as const,
            confidence: "high" as const,
            trigger_severity: "high" as const,
            alert_delivery_state: "failed" as const,
            alert_delivery_label: "Failed",
            risk_level: "HIGH",
            risk_score: 91,
            predicted_cases: 11,
            reason_flagged: "failed",
            trigger_reason: "Failed workflow",
            recommended_action: "Fix failure",
            recommended_response: "Fix failure",
            expected_operational_effect: "Retry",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 1,
            delivered_alert_count: 0,
            retry_pending_alert_count: 0,
            failed_alert_count: 1,
            queued_alert_count: 0,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:11:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:11:00Z",
          },
          {
            id: 203,
            public_id: "WF-203",
            ward_id: 13,
            ward_name: "C",
            status: "DELIVERED",
            decision_mode: "rule" as const,
            confidence: "high" as const,
            trigger_severity: "high" as const,
            alert_delivery_state: "delivered" as const,
            alert_delivery_label: "Delivered",
            risk_level: "HIGH",
            risk_score: 92,
            predicted_cases: 12,
            reason_flagged: "delivered",
            trigger_reason: "Delivered workflow",
            recommended_action: "Review trigger",
            recommended_response: "Review trigger",
            expected_operational_effect: "Active",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 1,
            delivered_alert_count: 1,
            retry_pending_alert_count: 0,
            failed_alert_count: 0,
            queued_alert_count: 0,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:12:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:12:00Z",
          },
          {
            id: 204,
            public_id: "WF-204",
            ward_id: 14,
            ward_name: "D",
            status: "RESOLVED",
            decision_mode: "rule" as const,
            confidence: "review" as const,
            trigger_severity: "review" as const,
            alert_delivery_state: "delivered" as const,
            alert_delivery_label: "Delivered",
            risk_level: "LOW",
            risk_score: 5,
            predicted_cases: 0,
            reason_flagged: "resolved",
            trigger_reason: "Resolved workflow",
            recommended_action: "No action",
            recommended_response: "No action",
            expected_operational_effect: "Resolved",
            rules_basis: "risk_threshold" as const,
            trigger_reason_items: [],
            eligible_actions: [],
            active_alert_count: 0,
            delivered_alert_count: 1,
            retry_pending_alert_count: 0,
            failed_alert_count: 0,
            queued_alert_count: 0,
            triggered_at: null,
            latest_risk_update_at: "2026-04-27T10:13:00Z",
            last_manual_request_at: null,
            updated_at: "2026-04-27T10:13:00Z",
          },
        ],
      });

    const response = await GET(new Request("http://localhost:3000/api/dashboard/wards?county=Migori"));
    const payload = await response.json();

    expect(response.status).toBe(200);
    expect(payload.wardQueue.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: 11, trigger_state: "ACTION_IN_PROGRESS", requires_action: true }),
        expect.objectContaining({ id: 12, trigger_state: "ACTION_IN_PROGRESS", requires_action: true }),
        expect.objectContaining({ id: 13, trigger_state: "TRIGGER_ACTIVE", requires_action: false }),
        expect.objectContaining({ id: 14, trigger_state: "RESOLVED", requires_action: false }),
      ]),
    );
    expect(payload.wardQueue.summary).toEqual({
      wards_requiring_action: 2,
      workflow_active_wards: 3,
      alerts_pending: 1,
    });
  });
});
