# Generated by Django 5.2.13 on 2026-04-19 15:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('county', models.CharField(default='Migori', max_length=120)),
                ('sub_county', models.CharField(blank=True, max_length=120)),
                ('ward_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('current_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('current_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('flood_indicator', models.FloatField(default=0.0)),
                ('predicted_cases', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('MODEL', 'Model'), ('MANUAL', 'Manual')], default='MODEL', max_length=20)),
                ('model_version', models.CharField(default='v0', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='risk.ward')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CHV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chvs', to='risk.ward')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('DASHBOARD', 'Dashboard')], default='SMS', max_length=20)),
                ('recipient', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='risk.riskscore')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risk.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['generated_at'], name='risk_risksc_generat_c59509_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['risk_level'], name='risk_risksc_risk_le_85a317_idx'),
        ),
    ]
