# Generated by Django 5.2.13 on 2026-04-20 23:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('HEALTH_CENTER', 'Health Center'), ('DISPENSARY', 'Dispensary'), ('CLINIC', 'Clinic')], default='DISPENSARY', max_length=20)),
                ('ownership', models.CharField(choices=[('PUBLIC', 'Public'), ('FAITH_BASED', 'Faith Based'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('level', models.CharField(choices=[('LEVEL_2', 'Level 2'), ('LEVEL_3', 'Level 3'), ('LEVEL_4', 'Level 4'), ('LEVEL_5', 'Level 5')], default='LEVEL_2', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facilities', to='risk.ward')),
            ],
            options={
                'ordering': ['ward__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='triagesession',
            name='referral_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_sessions', to='risk.healthfacility'),
        ),
        migrations.AddIndex(
            model_name='healthfacility',
            index=models.Index(fields=['facility_type', 'is_active'], name='risk_health_facilit_51c9a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthfacility',
            constraint=models.UniqueConstraint(fields=('ward', 'name'), name='unique_facility_name_per_ward'),
        ),
    ]
