# Generated by Django 5.2.13 on 2026-04-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_add_public_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('RAINFALL', 'Rainfall')], default='RAINFALL', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('source_mode', models.CharField(default='hybrid', max_length=20)),
                ('source_priority', models.JSONField(blank=True, default=list)),
                ('requested_wards', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['run_type', 'started_at'], name='risk_ingest_run_typ_8584b7_idx'), models.Index(fields=['status', 'started_at'], name='risk_ingest_status_884efd_idx')],
            },
        ),
    ]
