# Generated by Django 5.2.13 on 2026-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_modelrun_riskscore_model_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='feature_schema_version',
            field=models.CharField(default='mock-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='inference_dataset_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='training_dataset_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
