# Generated by Django 5.2.13 on 2026-04-25 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_etlheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('horizon_days', models.PositiveSmallIntegerField(default=7)),
                ('projected_case_burden', models.PositiveIntegerField(default=0)),
                ('projected_pressure_score', models.PositiveSmallIntegerField(default=0)),
                ('projected_readiness_state', models.CharField(choices=[('low', 'Low'), ('watch', 'Watch'), ('capacity_concern', 'Capacity Concern')], default='low', max_length=32)),
                ('surge_threshold_state', models.JSONField(blank=True, default=dict)),
                ('driving_ward_ids', models.JSONField(blank=True, default=list)),
                ('forecast_factors', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('freshness_state', models.CharField(default='UNKNOWN', max_length=20)),
                ('forecast_mode', models.CharField(default='negative_binomial_baseline_preview', max_length=80)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(default='negative-binomial-baseline', max_length=120)),
                ('model_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('horizon_days', models.PositiveSmallIntegerField(default=7)),
                ('feature_schema_version', models.CharField(default='facility-burden-v1', max_length=50)),
                ('feature_keys', models.JSONField(blank=True, default=list)),
                ('target_definition', models.CharField(default='expected_suspected_cases_per_facility_7d', max_length=160)),
                ('training_row_count', models.PositiveIntegerField(default=0)),
                ('inference_row_count', models.PositiveIntegerField(default=0)),
                ('evaluation_metrics', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='facilityforecast',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_forecasts', to='risk.healthfacility'),
        ),
        migrations.AddIndex(
            model_name='facilityforecastrun',
            index=models.Index(fields=['model_version', 'started_at'], name='risk_facili_model_v_0fdc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityforecastrun',
            index=models.Index(fields=['status', 'started_at'], name='risk_facili_status_801c26_idx'),
        ),
        migrations.AddField(
            model_name='facilityforecast',
            name='forecast_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='risk.facilityforecastrun'),
        ),
        migrations.AddIndex(
            model_name='facilityforecast',
            index=models.Index(fields=['generated_at'], name='risk_facili_generat_bc3e82_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityforecast',
            index=models.Index(fields=['projected_readiness_state', 'generated_at'], name='risk_facili_project_b0f3d8_idx'),
        ),
    ]
