# Generated by Django 5.2.13 on 2026-04-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_chvcoveragerequest_chvassignment_and_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertworkflowevent',
            new_name='risk_alertw_action_0fd299_idx',
            old_name='risk_alertw_action_2f5b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='alertworkflowevent',
            new_name='risk_alertw_workflo_6b2502_idx',
            old_name='risk_alertw_workflo_20d4bc_idx',
        ),
        migrations.RenameIndex(
            model_name='alertworkflowstate',
            new_name='risk_alertw_status_e1f730_idx',
            old_name='risk_alertw_status_4caea4_idx',
        ),
        migrations.RenameIndex(
            model_name='alertworkflowstate',
            new_name='risk_alertw_trigger_5edc07_idx',
            old_name='risk_alertw_trigger__3af095_idx',
        ),
        migrations.RenameIndex(
            model_name='alertworkflowstate',
            new_name='risk_alertw_last_ev_6ec3eb_idx',
            old_name='risk_alertw_last_ev_f193f9_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotification',
            new_name='risk_dashbo_state_3b7e2a_idx',
            old_name='risk_dashbo_state_7b7735_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotification',
            new_name='risk_dashbo_severit_a97a66_idx',
            old_name='risk_dashbo_severit_8651e9_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotification',
            new_name='risk_dashbo_recipie_d35549_idx',
            old_name='risk_dashbo_recipie_37d832_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotificationevent',
            new_name='risk_dashbo_action_519362_idx',
            old_name='risk_dashbo_action_3d0109_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardnotificationevent',
            new_name='risk_dashbo_notific_717f2c_idx',
            old_name='risk_dashbo_notific_56a5fc_idx',
        ),
        migrations.RenameIndex(
            model_name='etlheartbeat',
            new_name='risk_etlhea_compone_b6ab7e_idx',
            old_name='risk_etlhea_compone_63f67b_idx',
        ),
        migrations.RenameIndex(
            model_name='etlheartbeat',
            new_name='risk_etlhea_status_9563ba_idx',
            old_name='risk_etlhea_status_0b2913_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredataset',
            new_name='risk_featur_dataset_9ba424_idx',
            old_name='risk_featur_dataset_a593ec_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredataset',
            new_name='risk_featur_schema__c1e416_idx',
            old_name='risk_featur_schema__9c9241_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredatasetrow',
            new_name='risk_featur_dataset_59dd6f_idx',
            old_name='risk_featur_dataset_3e8f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredatasetrow',
            new_name='risk_featur_dataset_c5ae80_idx',
            old_name='risk_featur_dataset_d11a21_idx',
        ),
        migrations.RenameIndex(
            model_name='scenariosimulationrun',
            new_name='risk_scenar_scenari_d7f41a_idx',
            old_name='risk_scenar_scenari_b31731_idx',
        ),
        migrations.RenameIndex(
            model_name='wardgeometrydatasetversion',
            new_name='risk_wardge_dataset_db2257_idx',
            old_name='risk_wardge_dataset_b9f742_idx',
        ),
        migrations.RenameIndex(
            model_name='wardgeometrydatasetversion',
            new_name='risk_wardge_is_acti_1da632_idx',
            old_name='risk_wardge_is_acti_9e3e58_idx',
        ),
        migrations.RenameIndex(
            model_name='wardgeometryfeature',
            new_name='risk_wardge_dataset_6a1d72_idx',
            old_name='risk_wardge_dataset_a1a146_idx',
        ),
        migrations.RenameIndex(
            model_name='wardgeometryfeature',
            new_name='risk_wardge_dataset_e71bca_idx',
            old_name='risk_wardge_dataset_0e1af9_idx',
        ),
    ]
