# Generated by Django 5.2.13 on 2026-04-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_rename_risk_alertw_action_2f5b2c_idx_risk_alertw_action_0fd299_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnotification',
            name='type',
            field=models.CharField(choices=[('WARD_RISK_HIGH', 'Ward Risk High'), ('ALERT_FAILED', 'Alert Failed'), ('ALERT_RETRY_PENDING', 'Alert Retry Pending'), ('FEED_STALE', 'Feed Stale'), ('CHV_COVERAGE_REQUEST_STATUS', 'CHV Coverage Request Status')], max_length=40),
        ),
        migrations.CreateModel(
            name='CHVCoverageRequestEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=20)),
                ('delivery_backend', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='risk.chvcoveragerequest')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='risk.chvcoveragerequestevent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chv_coverage_request_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coverage_request', 'created_at'], name='risk_chvema_coverag_2f1f3e_idx'), models.Index(fields=['status', 'created_at'], name='risk_chvema_status_9a6a3b_idx')],
            },
        ),
    ]
