# Generated by Django 5.2.13 on 2026-04-28 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0022_alter_dashboardnotification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CHVCoverageRequestAlertLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chv_coverage_request_links",
                        to="risk.alert",
                    ),
                ),
                (
                    "coverage_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_alert_links",
                        to="risk.chvcoveragerequest",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chv_coverage_request_alert_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="chvcoveragerequestalertlink",
            constraint=models.UniqueConstraint(
                fields=("coverage_request", "alert"),
                name="unique_chv_coverage_request_alert_link",
            ),
        ),
        migrations.AddIndex(
            model_name="chvcoveragerequestalertlink",
            index=models.Index(
                fields=["coverage_request", "created_at"],
                name="risk_chvalink_cov_c4879f",
            ),
        ),
        migrations.AddIndex(
            model_name="chvcoveragerequestalertlink",
            index=models.Index(
                fields=["alert", "created_at"],
                name="risk_chvalink_alt_0730cb",
            ),
        ),
    ]
