# Generated by Codex on 2026-04-29

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0027_chvmessage_delivery_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("SYSTEM", "System")],
                        default="SMS",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(max_length=120)),
                ("source_reference", models.CharField(blank=True, max_length=160)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="risk.healthfacility",
                    ),
                ),
            ],
            options={
                "ordering": ["facility__name", "-is_verified", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="facilitycontact",
            index=models.Index(fields=["facility", "is_active", "is_verified"], name="risk_facili_facilit_3ecbd6_idx"),
        ),
        migrations.AddIndex(
            model_name="facilitycontact",
            index=models.Index(fields=["source", "source_reference"], name="risk_facili_source_301278_idx"),
        ),
        migrations.AddConstraint(
            model_name="facilitycontact",
            constraint=models.CheckConstraint(
                check=models.Q(phone__gt="") | models.Q(email__gt=""),
                name="facility_contact_requires_phone_or_email",
            ),
        ),
    ]
