# Generated by Django 5.2.13 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0029_facilityreadinessreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chvcoveragerequestevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ALERT_LINKAGE_ATTACHED", "Alert Linkage Attached"),
                    ("ALERT_LINKAGE_REDIRECTED", "Alert Linkage Redirected"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("RESOLVED", "Resolved"),
                    ("OWNERSHIP_CHANGED", "Ownership Changed"),
                    ("ASSIGNMENT_CREATED", "Assignment Created"),
                    ("ASSIGNMENT_COMPLETED", "Assignment Completed"),
                    ("ASSIGNMENT_CANCELLED", "Assignment Cancelled"),
                ],
                max_length=32,
            ),
        ),
    ]
