# Generated by Django 5.2.13 on 2026-04-29 11:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0030_alter_chvcoveragerequestevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityreadinessreviewevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('UPDATE_REQUEST_CREATED', 'Update Request Created')], max_length=30),
        ),
        migrations.CreateModel(
            name='FacilityReadinessUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('SYSTEM', 'System')], default='SMS', max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_update_requests', to='risk.facilitycontact')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_update_requests', to='risk.healthfacility')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_readiness_update_requests', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_requests', to='risk.facilityreadinessreview')),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='risk_facupd_status_idx'), models.Index(fields=['review', 'status'], name='risk_facupd_review_idx'), models.Index(fields=['facility', 'status'], name='risk_facupd_facility_idx')],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'QUEUED', 'SENT'])), fields=('review',), name='unique_active_facility_update_request_per_review'),
                    models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'QUEUED', 'SENT'])), fields=('facility',), name='unique_active_facility_update_request_per_facility'),
                ],
            },
        ),
    ]
