# Generated by Django 5.2.13 on 2026-04-29 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0031_alter_facilityreadinessreviewevent_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityreadinessreviewevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('UPDATE_REQUEST_CREATED', 'Update Request Created'), ('ESCALATION_CREATED', 'Escalation Created'), ('ESCALATION_ACKNOWLEDGED', 'Escalation Acknowledged'), ('ESCALATION_RESOLVED', 'Escalation Resolved'), ('ESCALATION_DISMISSED', 'Escalation Dismissed')], max_length=30),
        ),
        migrations.CreateModel(
            name='FacilityReadinessEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_readiness_escalations_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_readiness_escalations_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_readiness_escalations_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_escalations', to='risk.healthfacility')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='risk.facilityreadinessreview')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_readiness_escalations', to='risk.ward')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='risk_facesc_status_idx'), models.Index(fields=['facility', 'status'], name='risk_facesc_facility_idx'), models.Index(fields=['ward', 'status'], name='risk_facesc_ward_idx'), models.Index(fields=['assigned_to', 'status'], name='risk_facesc_assign_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKNOWLEDGED'])), fields=('review',), name='unique_active_facility_escalation_per_review'), models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKNOWLEDGED'])), fields=('facility',), name='unique_active_facility_escalation_per_facility')],
            },
        ),
    ]
