# Generated by Codex on 2026-05-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0032_alter_facilityreadinessreviewevent_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemControlState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "control_key",
                    models.CharField(
                        choices=[("ALERT_DELIVERY_PAUSE", "Alert delivery pause")],
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_control_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["control_key"],
                "indexes": [
                    models.Index(fields=["control_key", "is_active"], name="risk_system_control_key_idx"),
                    models.Index(fields=["active_until"], name="risk_system_active_until_idx"),
                ],
            },
        ),
    ]
