# Generated by Codex on 2026-05-02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0033_systemcontrolstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationExposureSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("population_baseline", "Population baseline"),
                            ("gridded_population", "Gridded population"),
                            ("settlement_layer", "Settlement layer"),
                            ("wash_vulnerability_layer", "WASH vulnerability layer"),
                            ("water_body_distance_layer", "Water body distance layer"),
                            ("flood_exposure_layer", "Flood exposure layer"),
                            ("catchment_mapping", "Catchment mapping"),
                            ("csv_backfill", "CSV backfill"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("release_version", models.CharField(blank=True, max_length=120)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("operator_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-submitted_at", "source_name"],
                "indexes": [
                    models.Index(fields=["source_type", "release_version"], name="risk_popsrc_type_release_idx"),
                    models.Index(fields=["source_name", "submitted_at"], name="risk_popsrc_name_sub_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PopulationExposureIngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("population_baseline", "Population baseline"),
                            ("gridded_population", "Gridded population"),
                            ("settlement_layer", "Settlement layer"),
                            ("wash_vulnerability_layer", "WASH vulnerability layer"),
                            ("water_body_distance_layer", "Water body distance layer"),
                            ("flood_exposure_layer", "Flood exposure layer"),
                            ("catchment_mapping", "Catchment mapping"),
                            ("csv_backfill", "CSV backfill"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("release_version", models.CharField(blank=True, max_length=120)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("adapter_key", models.CharField(default="csv", max_length=80)),
                ("input_ref", models.CharField(blank=True, max_length=255)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("replay", "Replay"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "correction_mode",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("amendment", "Amendment"),
                            ("backfill", "Backfill"),
                            ("release_replacement", "Release replacement"),
                        ],
                        default="original",
                        max_length=40,
                    ),
                ),
                ("replacement_reason", models.TextField(blank=True)),
                ("fallback_used", models.BooleanField(default=False)),
                ("records_seen", models.PositiveIntegerField(default=0)),
                ("records_loaded", models.PositiveIntegerField(default=0)),
                ("records_rejected", models.PositiveIntegerField(default=0)),
                ("operator_note", models.TextField(blank=True)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("rejected_rows", models.JSONField(blank=True, default=list)),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replaces_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_runs",
                        to="risk.populationexposureingestionrun",
                    ),
                ),
                (
                    "replay_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replay_runs",
                        to="risk.populationexposureingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="risk.populationexposuresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["source_type", "started_at"], name="risk_popexp_type_started_idx"),
                    models.Index(fields=["status", "started_at"], name="risk_popexp_status_started_idx"),
                    models.Index(fields=["correction_mode", "started_at"], name="risk_popexp_corr_started_idx"),
                    models.Index(fields=["release_version", "started_at"], name="risk_popexp_rel_started_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            ~models.Q(correction_mode="release_replacement")
                            | (
                                models.Q(replaces_run_id__isnull=False)
                                & ~models.Q(replacement_reason="")
                                & ~models.Q(release_version="")
                                & ~models.Q(source_ref="")
                            )
                        ),
                        name="risk_popexp_repl_required",
                    ),
                    models.CheckConstraint(
                        check=models.Q(replaces_run_id__isnull=True) | models.Q(correction_mode="release_replacement"),
                        name="risk_popexp_repl_only",
                    ),
                ],
            },
        ),
    ]
