# Generated by Codex on 2026-05-02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


TRUTH_CHOICES = [
    ("direct_population_baseline", "Direct population baseline"),
    ("spatially_aggregated_source", "Spatially aggregated source"),
    ("derived_exposure_proxy", "Derived exposure proxy"),
    ("manual_override", "Manual override"),
    ("seeded_demo", "Seeded demo"),
]

SOURCE_KIND_CHOICES = [
    ("live", "Live"),
    ("backfill", "Backfill"),
    ("seeded", "Seeded"),
]

FRESHNESS_CHOICES = [
    ("fresh", "Fresh"),
    ("delayed", "Delayed"),
    ("stale", "Stale"),
    ("replaced_by_new_release", "Replaced by new release"),
    ("replay_diagnostic", "Replay diagnostic"),
    ("replacement_not_activated", "Replacement not activated"),
    ("unknown", "Unknown"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0034_population_exposure_ingestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationBaselineRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("population_total", models.PositiveIntegerField()),
                ("population_under_five", models.PositiveIntegerField(blank=True, null=True)),
                ("household_count_proxy", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "truth_class",
                    models.CharField(
                        choices=TRUTH_CHOICES,
                        default="direct_population_baseline",
                        max_length=40,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_kind",
                    models.CharField(
                        choices=SOURCE_KIND_CHOICES,
                        default="live",
                        max_length=20,
                    ),
                ),
                (
                    "freshness_state",
                    models.CharField(
                        choices=FRESHNESS_CHOICES,
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("release_version", models.CharField(blank=True, max_length=120)),
                ("supersedes_record_ref", models.CharField(blank=True, max_length=160)),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_baseline_records",
                        to="risk.populationexposureingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_baseline_records",
                        to="risk.populationexposuresource",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_baselines",
                        to="risk.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "ward__name"],
                "indexes": [
                    models.Index(fields=["ward", "recorded_at"], name="risk_popbase_ward_recorded_idx"),
                    models.Index(fields=["truth_class", "recorded_at"], name="risk_popbase_truth_idx"),
                    models.Index(fields=["release_version", "recorded_at"], name="risk_popbase_release_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=~models.Q(truth_class="derived_exposure_proxy"),
                        name="risk_popbase_no_proxy",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExposureFeatureRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "exposure_type",
                    models.CharField(
                        choices=[
                            ("population_density", "Population density"),
                            ("settlement_concentration", "Settlement concentration"),
                            ("floodplain_exposure", "Floodplain exposure"),
                            ("water_body_proximity", "Water body proximity"),
                            ("wash_vulnerability", "WASH vulnerability"),
                            ("exposed_population_proxy", "Exposed population proxy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("exposure_value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=40)),
                (
                    "truth_class",
                    models.CharField(
                        choices=TRUTH_CHOICES,
                        default="derived_exposure_proxy",
                        max_length=40,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_kind",
                    models.CharField(
                        choices=SOURCE_KIND_CHOICES,
                        default="live",
                        max_length=20,
                    ),
                ),
                (
                    "freshness_state",
                    models.CharField(
                        choices=FRESHNESS_CHOICES,
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("aggregation_method", models.CharField(blank=True, max_length=120)),
                ("spatial_resolution", models.CharField(blank=True, max_length=120)),
                ("release_version", models.CharField(blank=True, max_length=120)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exposure_feature_records",
                        to="risk.populationexposureingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exposure_feature_records",
                        to="risk.populationexposuresource",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exposure_feature_records",
                        to="risk.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "ward__name", "exposure_type"],
                "indexes": [
                    models.Index(fields=["ward", "exposure_type", "recorded_at"], name="risk_expfeat_ward_type_idx"),
                    models.Index(fields=["truth_class", "recorded_at"], name="risk_expfeat_truth_idx"),
                    models.Index(fields=["release_version", "recorded_at"], name="risk_expfeat_release_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=~models.Q(truth_class="direct_population_baseline"),
                        name="risk_expfeat_no_direct",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CatchmentPopulationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("catchment_population_estimate", models.FloatField()),
                ("catchment_under_five_estimate", models.FloatField(blank=True, null=True)),
                ("assigned_ward_ids", models.JSONField(blank=True, default=list)),
                ("assignment_method", models.CharField(blank=True, max_length=120)),
                (
                    "truth_class",
                    models.CharField(
                        choices=TRUTH_CHOICES,
                        default="derived_exposure_proxy",
                        max_length=40,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_kind",
                    models.CharField(
                        choices=SOURCE_KIND_CHOICES,
                        default="live",
                        max_length=20,
                    ),
                ),
                (
                    "freshness_state",
                    models.CharField(
                        choices=FRESHNESS_CHOICES,
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("release_version", models.CharField(blank=True, max_length=120)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catchment_population_records",
                        to="risk.healthfacility",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catchment_population_records",
                        to="risk.populationexposureingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catchment_population_records",
                        to="risk.populationexposuresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "facility__name"],
                "indexes": [
                    models.Index(fields=["facility", "recorded_at"], name="risk_catchpop_fac_record_idx"),
                    models.Index(fields=["truth_class", "recorded_at"], name="risk_catchpop_truth_idx"),
                    models.Index(fields=["release_version", "recorded_at"], name="risk_catchpop_release_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=~models.Q(truth_class="direct_population_baseline"),
                        name="risk_catchpop_no_direct",
                    ),
                ],
            },
        ),
    ]
