# Generated by Codex on 2026-05-03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0035_canonical_population_exposure_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("weekly_aggregate", "Weekly aggregate"),
                            ("daily_aggregate", "Daily aggregate"),
                            ("line_list_summary", "Line-list summary"),
                            ("trusted_push", "Trusted push"),
                            ("csv_backfill", "CSV backfill"),
                            ("field_signal", "Field signal"),
                            ("facility_proxy", "Facility proxy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reporting_period_start", models.DateField(blank=True, null=True)),
                ("reporting_period_end", models.DateField(blank=True, null=True)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("operator_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-submitted_at", "source_name"],
                "indexes": [
                    models.Index(fields=["source_type", "reporting_period_start"], name="risk_survsrc_type_period_idx"),
                    models.Index(fields=["source_name", "submitted_at"], name="risk_survsrc_name_sub_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            models.Q(reporting_period_start__isnull=True)
                            | models.Q(reporting_period_end__isnull=True)
                            | models.Q(reporting_period_start__lte=models.F("reporting_period_end"))
                        ),
                        name="risk_survsrc_period_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveillanceIngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("weekly_aggregate", "Weekly aggregate"),
                            ("daily_aggregate", "Daily aggregate"),
                            ("line_list_summary", "Line-list summary"),
                            ("trusted_push", "Trusted push"),
                            ("csv_backfill", "CSV backfill"),
                            ("field_signal", "Field signal"),
                            ("facility_proxy", "Facility proxy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                ("reporting_period_start", models.DateField(blank=True, null=True)),
                ("reporting_period_end", models.DateField(blank=True, null=True)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("adapter_key", models.CharField(default="surveillance_csv", max_length=80)),
                ("input_ref", models.CharField(blank=True, max_length=255)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("replay", "Replay"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "correction_mode",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("amendment", "Amendment"),
                            ("backfill", "Backfill"),
                        ],
                        default="original",
                        max_length=40,
                    ),
                ),
                ("correction_reason", models.TextField(blank=True)),
                ("fallback_used", models.BooleanField(default=False)),
                ("records_seen", models.PositiveIntegerField(default=0)),
                ("records_loaded", models.PositiveIntegerField(default=0)),
                ("records_rejected", models.PositiveIntegerField(default=0)),
                ("operator_note", models.TextField(blank=True)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("rejected_rows", models.JSONField(blank=True, default=list)),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replay_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replay_runs",
                        to="risk.surveillanceingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="risk.surveillancesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["source_type", "started_at"], name="risk_survrun_type_started_idx"),
                    models.Index(fields=["status", "started_at"], name="risk_survrun_status_idx"),
                    models.Index(fields=["correction_mode", "started_at"], name="risk_survrun_corr_started_idx"),
                    models.Index(fields=["reporting_period_start"], name="risk_survrun_period_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            models.Q(reporting_period_start__isnull=True)
                            | models.Q(reporting_period_end__isnull=True)
                            | models.Q(reporting_period_start__lte=models.F("reporting_period_end"))
                        ),
                        name="risk_survrun_period_order",
                    ),
                    models.CheckConstraint(
                        check=~models.Q(correction_mode="amendment") | ~models.Q(correction_reason=""),
                        name="risk_survrun_amend_reason",
                    ),
                ],
            },
        ),
    ]
