# Generated by Codex on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


TRUTH_LEVEL_CHOICES = [
    ("confirmed_surveillance", "Confirmed surveillance"),
    ("suspected_surveillance", "Suspected surveillance"),
    ("proxy_diarrheal_signal", "Proxy diarrheal signal"),
    ("field_signal_only", "Field signal only"),
    ("seeded_demo", "Seeded demo"),
]

SOURCE_KIND_CHOICES = [
    ("live", "Live"),
    ("backfill", "Backfill"),
    ("seeded", "Seeded"),
]

FRESHNESS_CHOICES = [
    ("fresh", "Fresh"),
    ("delayed", "Delayed"),
    ("stale", "Stale"),
    ("corrected_after_initial_submission", "Corrected after initial submission"),
    ("replay_diagnostic", "Replay diagnostic"),
    ("unknown", "Unknown"),
]

DISEASE_CATEGORY_CHOICES = [
    ("cholera", "Cholera"),
    ("diarrheal", "Diarrheal"),
]

CASE_CLASS_CHOICES = [
    ("suspected", "Suspected"),
    ("confirmed", "Confirmed"),
    ("proxy", "Proxy"),
]

GRANULARITY_CHOICES = [
    ("day", "Day"),
    ("week", "Week"),
]

OUTBREAK_LABEL_CHOICES = [
    ("none", "None"),
    ("watch", "Watch"),
    ("active", "Active"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0036_surveillance_ingestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "disease_category",
                    models.CharField(choices=DISEASE_CATEGORY_CHOICES, max_length=20),
                ),
                (
                    "case_class",
                    models.CharField(choices=CASE_CLASS_CHOICES, max_length=20),
                ),
                (
                    "outbreak_label",
                    models.CharField(choices=OUTBREAK_LABEL_CHOICES, default="none", max_length=20),
                ),
                ("count_value", models.PositiveIntegerField()),
                ("reporting_period_start", models.DateField()),
                ("reporting_period_end", models.DateField()),
                (
                    "reporting_granularity",
                    models.CharField(choices=GRANULARITY_CHOICES, default="week", max_length=10),
                ),
                (
                    "truth_level",
                    models.CharField(
                        choices=TRUTH_LEVEL_CHOICES,
                        default="suspected_surveillance",
                        max_length=40,
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                (
                    "source_kind",
                    models.CharField(choices=SOURCE_KIND_CHOICES, default="live", max_length=20),
                ),
                (
                    "freshness_state",
                    models.CharField(choices=FRESHNESS_CHOICES, default="unknown", max_length=50),
                ),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("supersedes_record_ref", models.CharField(blank=True, max_length=160)),
                ("source_ref", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveillance_records",
                        to="risk.healthfacility",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveillance_records",
                        to="risk.surveillanceingestionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveillance_records",
                        to="risk.surveillancesource",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveillance_records",
                        to="risk.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-reporting_period_end", "ward__name", "case_class"],
                "indexes": [
                    models.Index(fields=["ward", "reporting_period_start", "reporting_period_end"], name="risk_survrec_ward_period_idx"),
                    models.Index(fields=["facility", "reporting_period_start"], name="risk_survrec_fac_period_idx"),
                    models.Index(fields=["truth_level", "reporting_period_start"], name="risk_survrec_truth_period_idx"),
                    models.Index(fields=["source", "created_at"], name="risk_survrec_src_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(reporting_period_start__lte=models.F("reporting_period_end")),
                        name="risk_survrec_period_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveillanceLabelWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label_window_start", models.DateField()),
                ("label_window_end", models.DateField()),
                ("suspected_case_count", models.PositiveIntegerField(default=0)),
                ("confirmed_case_count", models.PositiveIntegerField(default=0)),
                ("proxy_case_count", models.PositiveIntegerField(default=0)),
                (
                    "outbreak_label",
                    models.CharField(choices=OUTBREAK_LABEL_CHOICES, default="none", max_length=20),
                ),
                (
                    "label_truth_level",
                    models.CharField(
                        choices=TRUTH_LEVEL_CHOICES,
                        default="suspected_surveillance",
                        max_length=40,
                    ),
                ),
                ("generation_mode", models.CharField(default="phase_2_shape_defined", max_length=40)),
                ("source_coverage_summary", models.JSONField(blank=True, default=dict)),
                ("generated_from_record_refs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveillance_label_windows",
                        to="risk.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-label_window_end", "ward__name"],
                "indexes": [
                    models.Index(fields=["ward", "label_window_start", "label_window_end"], name="risk_survlbl_ward_window_idx"),
                    models.Index(fields=["outbreak_label", "label_window_end"], name="risk_survlbl_outbreak_idx"),
                    models.Index(fields=["label_truth_level", "label_window_end"], name="risk_survlbl_truth_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(label_window_start__lte=models.F("label_window_end")),
                        name="risk_survlbl_window_order",
                    ),
                ],
            },
        ),
    ]
