# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0038_surveillance_label_dataset_lineage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveillanceingestionrun",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scheduled", "Scheduled"),
                    ("trusted_push", "Trusted push"),
                    ("replay", "Replay"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
