# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0039_surveillance_trusted_push_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskscore",
            name="decision_policy",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="systemcontrolstate",
            name="control_key",
            field=models.CharField(
                choices=[
                    ("ALERT_DELIVERY_PAUSE", "Alert delivery pause"),
                    ("WARD_RISK_DECISION_POLICY", "Ward risk decision policy"),
                ],
                max_length=80,
                unique=True,
            ),
        ),
    ]
