# Generated by Django 5.2.13 on 2026-05-03 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_decision_policy_trace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparednessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('chv_follow_up', 'CHV follow-up'), ('household_prevention_message', 'Household prevention message'), ('facility_ors_review', 'Facility ORS review'), ('facility_staffing_review', 'Facility staffing review'), ('county_escalation', 'County escalation'), ('water_treatment_distribution', 'Water treatment distribution'), ('surveillance_follow_up', 'Surveillance follow-up'), ('field_verification', 'Field verification')], max_length=64)),
                ('source_trigger_type', models.CharField(choices=[('manual', 'Manual'), ('alert', 'Alert'), ('alert_workflow', 'Alert workflow'), ('risk_score', 'Risk score'), ('chv_coverage_request', 'CHV coverage request'), ('facility_readiness_review', 'Facility readiness review'), ('facility_update_request', 'Facility update request'), ('facility_escalation', 'Facility escalation'), ('outcome_feedback', 'Outcome feedback'), ('system', 'System')], default='manual', max_length=64)),
                ('source_trigger_ref', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Escalated'), ('EXPIRED', 'Expired')], default='QUEUED', max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('assigned_to_team', models.CharField(blank=True, max_length=120)),
                ('decision_policy_version', models.CharField(blank=True, max_length=80)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_target_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('completion_evidence', models.JSONField(blank=True, default=dict)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('escalation_metadata', models.JSONField(blank=True, default=dict)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.alert')),
                ('alert_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.alertworkflowstate')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparedness_actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('chv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.chv')),
                ('chv_coverage_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.chvcoveragerequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparedness_actions_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.healthfacility')),
                ('facility_escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.facilityreadinessescalation')),
                ('facility_readiness_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.facilityreadinessreview')),
                ('facility_update_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.facilityreadinessupdaterequest')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparedness_actions', to='risk.modelrun')),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparedness_actions', to='risk.riskscore')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparedness_actions', to='risk.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparednessActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Escalated'), ('EXPIRED', 'Expired'), ('STATUS_CHANGED', 'Status Changed'), ('DUE_DATE_CHANGED', 'Due Date Changed'), ('COMPLETION_EVIDENCE_ADDED', 'Completion Evidence Added'), ('COMMENT', 'Comment')], max_length=40)),
                ('old_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(blank=True, max_length=24)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparedness_action_events', to=settings.AUTH_USER_MODEL)),
                ('preparedness_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='risk.preparednessaction')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['status', 'due_at'], name='risk_prepact_status_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['priority', 'due_at'], name='risk_prepact_prior_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['ward', 'status'], name='risk_prepact_ward_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['facility', 'status'], name='risk_prepact_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['assigned_to', 'status'], name='risk_prepact_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessaction',
            index=models.Index(fields=['source_trigger_type', 'source_trigger_ref'], name='risk_prepact_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='preparednessaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'QUEUED', 'ASSIGNED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'BLOCKED', 'ESCALATED']), models.Q(('source_trigger_ref', ''), _negated=True)), fields=('action_type', 'source_trigger_type', 'source_trigger_ref'), name='risk_prepact_src_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='preparednessactionevent',
            index=models.Index(fields=['preparedness_action', 'created_at'], name='risk_prepevt_action_idx'),
        ),
        migrations.AddIndex(
            model_name='preparednessactionevent',
            index=models.Index(fields=['event_type', 'created_at'], name='risk_prepevt_type_idx'),
        ),
    ]
