# Generated by Django 5.2.13 on 2026-05-03 22:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0045_operational_metric_mart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnotification',
            name='type',
            field=models.CharField(choices=[('WARD_RISK_HIGH', 'Ward Risk High'), ('ALERT_FAILED', 'Alert Failed'), ('ALERT_RETRY_PENDING', 'Alert Retry Pending'), ('FEED_STALE', 'Feed Stale'), ('CHV_COVERAGE_REQUEST_STATUS', 'CHV Coverage Request Status'), ('OPERATIONAL_KPI_THRESHOLD', 'Operational KPI Threshold')], max_length=40),
        ),
        migrations.CreateModel(
            name='OperationalThresholdBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('breach_key', models.CharField(blank=True, max_length=255, unique=True)),
                ('breach_type', models.CharField(choices=[('THRESHOLD_WARNING', 'Threshold warning'), ('THRESHOLD_BREACH', 'Threshold breach'), ('SOURCE_WARNING', 'Source warning'), ('SNAPSHOT_STALE', 'Snapshot stale'), ('MISSING_SNAPSHOT', 'Missing snapshot'), ('STATUS_WARNING', 'Status warning')], max_length=32)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField()),
                ('warning_code', models.CharField(blank=True, max_length=120)),
                ('observed_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('observed_status', models.CharField(blank=True, max_length=40)),
                ('observed_unit', models.CharField(blank=True, max_length=40)),
                ('comparator', models.CharField(blank=True, max_length=8)),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('warning_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('critical_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('threshold_key_snapshot', models.CharField(blank=True, max_length=120)),
                ('threshold_version_snapshot', models.CharField(blank=True, max_length=40)),
                ('metric_key_snapshot', models.SlugField(max_length=120)),
                ('metric_version_snapshot', models.CharField(max_length=40)),
                ('dimension_values', models.JSONField(blank=True, default=dict)),
                ('source_coverage', models.JSONField(blank=True, default=dict)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('evaluation_metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_breaches', to='risk.operationalmetricdefinition')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_breaches', to='risk.operationalmetricsnapshot')),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaches', to='risk.operationalslathreshold')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_threshold_breaches', to='risk.ward')),
            ],
            options={
                'ordering': ['-date', '-severity', 'metric_definition__metric_key'],
                'indexes': [models.Index(fields=['status', 'severity', 'date'], name='risk_opsbreach_state_idx'), models.Index(fields=['metric_definition', 'status'], name='risk_opsbreach_metric_idx'), models.Index(fields=['threshold', 'status'], name='risk_opsbreach_threshold_idx'), models.Index(fields=['snapshot', 'status'], name='risk_opsbreach_snapshot_idx'), models.Index(fields=['ward', 'status', 'date'], name='risk_opsbreach_ward_idx')],
            },
        ),
    ]
