# Generated by Django 5.2.13 on 2026-05-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0046_operational_threshold_breaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('observed', 'Observed'), ('forecast', 'Forecast'), ('derived_rolling_window', 'Derived rolling window'), ('derived_anomaly', 'Derived anomaly'), ('fallback_static', 'Fallback static')], default='observed', max_length=40)),
                ('source_provider', models.CharField(max_length=120)),
                ('source_kind', models.CharField(choices=[('LIVE', 'Live'), ('SEEDED', 'Seeded'), ('HYBRID', 'Hybrid'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('source_mode', models.CharField(blank=True, max_length=20)),
                ('issue_time', models.DateTimeField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('lead_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('forecast_horizon_days', models.PositiveSmallIntegerField(default=0)),
                ('rainfall_mm', models.FloatField()),
                ('quality_flag', models.CharField(choices=[('accepted', 'Accepted'), ('degraded_fallback', 'Degraded fallback'), ('missing_forecast_contract', 'Missing forecast contract'), ('missing_observed_timestamp', 'Missing observed timestamp'), ('derived', 'Derived'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('fallback_flag', models.BooleanField(default=False)),
                ('source_run', models.CharField(max_length=160)),
                ('source_ref', models.CharField(max_length=255)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='climate_records', to='risk.ingestionrun')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='climate_records', to='risk.ward')),
            ],
            options={
                'ordering': ['-valid_date', '-issue_time', 'ward__name', 'record_type'],
                'indexes': [models.Index(fields=['ward', 'record_type', 'valid_date'], name='risk_climrec_ward_type_idx'), models.Index(fields=['source_provider', 'issue_time'], name='risk_climrec_src_issue_idx'), models.Index(fields=['lead_day', 'valid_date'], name='risk_climrec_lead_valid_idx'), models.Index(fields=['fallback_flag', 'record_type'], name='risk_climrec_fallback_idx')],
                'constraints': [models.UniqueConstraint(fields=('ingestion_run', 'source_ref'), name='risk_climrec_run_ref_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'forecast'), _negated=True), models.Q(('issue_time__isnull', False), ('valid_date__isnull', False), ('lead_day__isnull', False)), _connector='OR'), name='risk_climrec_forecast_contract'), models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'observed'), _negated=True), ('observed_timestamp__isnull', False), _connector='OR'), name='risk_climrec_observed_contract'), models.CheckConstraint(condition=models.Q(models.Q(('record_type', 'fallback_static'), _negated=True), ('fallback_flag', True), _connector='OR'), name='risk_climrec_fallback_flag'), models.CheckConstraint(condition=models.Q(('lead_day__isnull', True), ('forecast_horizon_days__gte', models.F('lead_day')), _connector='OR'), name='risk_climrec_horizon_lead')],
            },
        ),
    ]
