# Generated by Django 5.2.13 on 2026-05-04 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0052_ussd_menu_version_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='conflict_state',
            field=models.CharField(choices=[('NONE', 'None'), ('REPLAYED', 'Replayed'), ('SCOPE_MISMATCH', 'Scope mismatch'), ('STALE_BUNDLE', 'Stale bundle'), ('UNSUPPORTED_UPLOAD', 'Unsupported upload')], default='NONE', max_length=32),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='contract_version',
            field=models.CharField(default='chv-offline-v1', max_length=64),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='download_bundle_version',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='server_receipt',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='upload_type',
            field=models.CharField(choices=[('symptom_triage', 'Symptom triage'), ('suspected_case_signal', 'Suspected case signal'), ('prevention_visit', 'Household prevention visit'), ('task_ack', 'Task acknowledgement'), ('alert_ack', 'Alert acknowledgement')], default='symptom_triage', max_length=40),
        ),
        migrations.CreateModel(
            name='CHVDeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(max_length=120)),
                ('contract_version', models.CharField(default='chv-offline-v1', max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web/PWA'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_bundle_version', models.CharField(blank=True, max_length=96)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_registrations', to='risk.chv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chv_device_registrations', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chv_device_registrations', to='risk.ward')),
            ],
            options={
                'ordering': ['-last_seen_at', '-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='device_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_queue_items', to='risk.chvdeviceregistration'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['device_registration', 'created_at'], name='risk_sync_device_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['upload_type', 'status'], name='risk_sync_upload_status_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['contract_version', 'created_at'], name='risk_sync_contract_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('source_device_id', 'idempotency_key'), name='unique_sync_idempotency_per_device'),
        ),
        migrations.AddIndex(
            model_name='chvdeviceregistration',
            index=models.Index(fields=['ward', 'is_active'], name='risk_chvdev_ward_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chvdeviceregistration',
            index=models.Index(fields=['chv', 'is_active'], name='risk_chvdev_chv_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chvdeviceregistration',
            index=models.Index(fields=['contract_version', 'last_seen_at'], name='risk_chvdev_contract_idx'),
        ),
        migrations.AddConstraint(
            model_name='chvdeviceregistration',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='risk_chvdev_user_device_uniq'),
        ),
    ]
