# Generated by Codex on 2026-05-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0053_chv_offline_contracts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CHVOfflineRejectedSubmissionAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_device_id", models.CharField(blank=True, max_length=120)),
                ("client_submission_id", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, max_length=160)),
                ("upload_type", models.CharField(blank=True, max_length=40)),
                ("contract_version", models.CharField(blank=True, max_length=64)),
                (
                    "rejection_stage",
                    models.CharField(
                        choices=[
                            ("ENVELOPE_VALIDATION", "Envelope validation"),
                            ("PAYLOAD_SCHEMA", "Payload schema"),
                            ("PII_MINIMIZATION", "PII minimization"),
                            ("CONTRACT_VERSION", "Contract version"),
                            ("WARD_SCOPE", "Ward scope"),
                            ("DEVICE_REGISTRATION", "Device registration"),
                        ],
                        default="ENVELOPE_VALIDATION",
                        max_length=40,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("safe_error_summary", models.TextField(blank=True)),
                ("field_paths", models.JSONField(blank=True, default=list)),
                ("status_code", models.PositiveSmallIntegerField(default=400)),
                ("request_body_hmac", models.CharField(blank=True, max_length=64)),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_submission_audits",
                        to="risk.chvdeviceregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chv_offline_rejected_submission_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chv_offline_rejected_submission_audits",
                        to="risk.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chvofflinerejectedsubmissionaudit",
            index=models.Index(fields=["ward", "created_at"], name="risk_chvrej_ward_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chvofflinerejectedsubmissionaudit",
            index=models.Index(fields=["user", "created_at"], name="risk_chvrej_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chvofflinerejectedsubmissionaudit",
            index=models.Index(fields=["source_device_id", "created_at"], name="risk_chvrej_device_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chvofflinerejectedsubmissionaudit",
            index=models.Index(fields=["rejection_stage", "created_at"], name="risk_chvrej_stage_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chvofflinerejectedsubmissionaudit",
            index=models.Index(fields=["request_body_hmac"], name="risk_chvrej_hmac_idx"),
        ),
    ]
