# Generated by Django 5.2.13 on 2026-05-04 14:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0054_chv_offline_rejected_submission_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_key', models.CharField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('system_type', models.CharField(choices=[('DHIS2', 'DHIS2'), ('CSV_PARTNER', 'CSV partner'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('owner', models.CharField(max_length=160)),
                ('default_exchange_format', models.CharField(default='CSV', max_length=40)),
                ('auth_config_reference', models.CharField(blank=True, max_length=160)),
                ('api_base_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_key'],
                'indexes': [models.Index(fields=['system_key', 'status'], name='risk_extsys_key_status_idx'), models.Index(fields=['system_type', 'status'], name='risk_extsys_type_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteroperabilityMappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interoperability_mapping_versions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_versions', to='risk.externalsystem')),
            ],
            options={
                'ordering': ['system__system_key', '-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalValueSetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value_set_key', models.CharField(max_length=120)),
                ('external_value', models.CharField(max_length=160)),
                ('external_label', models.CharField(blank=True, max_length=200)),
                ('internal_value', models.CharField(max_length=160)),
                ('internal_label', models.CharField(blank=True, max_length=200)),
                ('mapping_confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs review'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_value_set_mappings_reviewed', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_set_mappings', to='risk.externalsystem')),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_set_mappings', to='risk.interoperabilitymappingversion')),
            ],
            options={
                'ordering': ['system__system_key', 'value_set_key', 'internal_value'],
            },
        ),
        migrations.CreateModel(
            name='ExternalOrgUnitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_identifier', models.CharField(max_length=160)),
                ('external_display_name', models.CharField(blank=True, max_length=200)),
                ('internal_object_type', models.CharField(choices=[('WARD', 'Ward'), ('HEALTH_FACILITY', 'Health facility')], max_length=40)),
                ('internal_object_public_id', models.CharField(max_length=80)),
                ('internal_object_code', models.CharField(blank=True, max_length=80)),
                ('mapping_confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs review'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_mappings', to='risk.healthfacility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_org_unit_mappings_reviewed', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_mappings', to='risk.ward')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_unit_mappings', to='risk.externalsystem')),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_unit_mappings', to='risk.interoperabilitymappingversion')),
            ],
            options={
                'ordering': ['system__system_key', 'external_identifier'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDataElementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exchange_type', models.CharField(max_length=80)),
                ('external_identifier', models.CharField(max_length=160)),
                ('external_display_name', models.CharField(blank=True, max_length=200)),
                ('internal_field', models.CharField(max_length=120)),
                ('value_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date')], default='NUMBER', max_length=20)),
                ('required_for_exchange', models.BooleanField(default=True)),
                ('mapping_confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs review'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_data_element_mappings_reviewed', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_element_mappings', to='risk.externalsystem')),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_element_mappings', to='risk.interoperabilitymappingversion')),
            ],
            options={
                'ordering': ['system__system_key', 'exchange_type', 'internal_field'],
            },
        ),
        migrations.CreateModel(
            name='InteroperabilityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=20)),
                ('exchange_type', models.CharField(choices=[('surveillance_case_count_import', 'Surveillance case count import'), ('outbreak_label_import', 'Outbreak label import'), ('facility_import', 'Facility import'), ('ward_org_unit_mapping_import', 'Ward/org-unit mapping import'), ('population_exposure_import', 'Population/exposure import'), ('aggregate_report_export', 'Aggregate report export'), ('alert_action_summary_export', 'Alert/action summary export')], max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_CONFIRMATION', 'Ready for confirmation'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('RETRY_CREATED', 'Retry created')], default='DRAFT', max_length=40)),
                ('dry_run', models.BooleanField(default=True)),
                ('source_file_name', models.CharField(blank=True, max_length=200)),
                ('endpoint_url', models.CharField(blank=True, max_length=500)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_accepted', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('mapping_coverage', models.FloatField(default=0.0)),
                ('error_summary', models.TextField(blank=True)),
                ('dry_run_preview', models.JSONField(blank=True, default=dict)),
                ('export_payload', models.JSONField(blank=True, default=dict)),
                ('connector_config', models.JSONField(blank=True, default=dict)),
                ('lineage_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interoperability_runs', to='risk.interoperabilitymappingversion')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interoperability_runs', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='risk.interoperabilityrun')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interoperability_runs', to='risk.externalsystem')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteroperabilityRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('external_identifier', models.CharField(blank=True, max_length=160)),
                ('internal_object_type', models.CharField(blank=True, max_length=40)),
                ('internal_object_public_id', models.CharField(blank=True, max_length=80)),
                ('internal_object_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNMAPPED', 'Unmapped'), ('PREVIEW', 'Preview')], max_length=20)),
                ('action', models.CharField(choices=[('IMPORT_MAPPING', 'Import mapping'), ('EXPORT_RECORD', 'Export record'), ('NOOP', 'No-op')], default='NOOP', max_length=40)),
                ('safe_context', models.JSONField(blank=True, default=dict)),
                ('source_record_ref', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='risk.interoperabilityrun')),
            ],
            options={
                'ordering': ['run', 'row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteroperabilityRunError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='ERROR', max_length=20)),
                ('error_code', models.CharField(max_length=80)),
                ('field_path', models.CharField(blank=True, max_length=160)),
                ('safe_message', models.TextField()),
                ('remediation_hint', models.TextField(blank=True)),
                ('raw_value_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='risk.interoperabilityrun')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='risk.interoperabilityrunitem')),
            ],
            options={
                'ordering': ['run', 'item__row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='interoperabilitymappingversion',
            index=models.Index(fields=['system', 'status'], name='risk_iopmapver_system_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilitymappingversion',
            index=models.Index(fields=['effective_date', 'status'], name='risk_iopmapver_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='interoperabilitymappingversion',
            constraint=models.UniqueConstraint(fields=('system', 'version_label'), name='risk_iopmapver_unique_label'),
        ),
        migrations.AddIndex(
            model_name='externalvaluesetmapping',
            index=models.Index(fields=['system', 'value_set_key', 'status'], name='risk_extval_valueset_idx'),
        ),
        migrations.AddIndex(
            model_name='externalvaluesetmapping',
            index=models.Index(fields=['external_value'], name='risk_extval_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalvaluesetmapping',
            constraint=models.UniqueConstraint(fields=('system', 'mapping_version', 'value_set_key', 'internal_value'), name='risk_extval_unique_internal'),
        ),
        migrations.AddConstraint(
            model_name='externalvaluesetmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_confidence__gte', 0), ('mapping_confidence__lte', 1)), name='risk_extval_confidence_range'),
        ),
        migrations.AddIndex(
            model_name='externalorgunitmapping',
            index=models.Index(fields=['system', 'status'], name='risk_extorg_system_status_idx'),
        ),
        migrations.AddIndex(
            model_name='externalorgunitmapping',
            index=models.Index(fields=['internal_object_type', 'internal_object_public_id'], name='risk_extorg_internal_idx'),
        ),
        migrations.AddIndex(
            model_name='externalorgunitmapping',
            index=models.Index(fields=['external_identifier'], name='risk_extorg_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalorgunitmapping',
            constraint=models.UniqueConstraint(fields=('system', 'mapping_version', 'external_identifier'), name='risk_extorg_unique_external'),
        ),
        migrations.AddConstraint(
            model_name='externalorgunitmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_confidence__gte', 0), ('mapping_confidence__lte', 1)), name='risk_extorg_confidence_range'),
        ),
        migrations.AddIndex(
            model_name='externaldataelementmapping',
            index=models.Index(fields=['system', 'exchange_type', 'status'], name='risk_extde_exchange_idx'),
        ),
        migrations.AddIndex(
            model_name='externaldataelementmapping',
            index=models.Index(fields=['external_identifier'], name='risk_extde_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldataelementmapping',
            constraint=models.UniqueConstraint(fields=('system', 'mapping_version', 'exchange_type', 'internal_field'), name='risk_extde_unique_internal'),
        ),
        migrations.AddConstraint(
            model_name='externaldataelementmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_confidence__gte', 0), ('mapping_confidence__lte', 1)), name='risk_extde_confidence_range'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrun',
            index=models.Index(fields=['direction', 'exchange_type', 'started_at'], name='risk_ioprun_exchange_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrun',
            index=models.Index(fields=['system', 'status', 'started_at'], name='risk_ioprun_system_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrun',
            index=models.Index(fields=['retry_of', 'created_at'], name='risk_ioprun_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrunitem',
            index=models.Index(fields=['run', 'status'], name='risk_iopitem_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrunitem',
            index=models.Index(fields=['external_identifier'], name='risk_iopitem_external_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrunitem',
            index=models.Index(fields=['internal_object_type', 'internal_object_public_id'], name='risk_iopitem_internal_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrunerror',
            index=models.Index(fields=['run', 'severity'], name='risk_ioperr_run_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='interoperabilityrunerror',
            index=models.Index(fields=['error_code', 'created_at'], name='risk_ioperr_code_idx'),
        ),
    ]
