# Generated by Django 5.2.13 on 2026-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0074_active_english_ussd_menu_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnotification',
            name='type',
            field=models.CharField(choices=[('WARD_RISK_HIGH', 'Ward Risk High'), ('ALERT_FAILED', 'Alert Failed'), ('ALERT_RETRY_PENDING', 'Alert Retry Pending'), ('FEED_STALE', 'Feed Stale'), ('CHV_COVERAGE_REQUEST_STATUS', 'CHV Coverage Request Status'), ('OPERATIONAL_KPI_THRESHOLD', 'Operational KPI Threshold'), ('SESSION_REPLAY_DETECTED', 'Session Replay Detected')], max_length=40),
        ),
    ]
