# Generated by Django 5.2.17 on 2026-08-08 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def populate_alert_idempotency_keys(apps, schema_editor):
    Alert = apps.get_model("risk", "Alert")
    for alert in Alert.objects.filter(idempotency_key__isnull=True).iterator():
        alert.idempotency_key = uuid.uuid4()
        alert.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0077_chirps_identity_and_ingestion_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='callback_payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alert',
            name='delivery_kind',
            field=models.CharField(choices=[('LIVE', 'Live provider'), ('SIMULATED', 'Simulated'), ('QUEUE_ONLY', 'Queue only')], default='LIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='idempotency_key',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_error_classification',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('simulated', 'Simulated'), ('not_applicable', 'Not applicable')], default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('simulated', 'Simulated'), ('unknown', 'Unknown')], default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_request_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='provider_response_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AlertDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('provider_event_id', models.CharField(blank=True, max_length=160)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('sanitized_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to='risk.alert')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['provider', 'provider_message_id'], name='risk_alertde_msg_idx'), models.Index(fields=['provider', 'provider_event_id'], name='risk_alertde_evt_idx'), models.Index(fields=['status', 'received_at'], name='risk_alertde_status_idx')],
            },
        ),
        migrations.RunPython(
            code=populate_alert_idempotency_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='alert',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
