from django.urls import path

from .views import (
    AccessRequestAPIView,
    AccessRequestApproveAPIView,
    AccessRequestListAPIView,
    AccessRequestOptionsAPIView,
    AccessRequestRejectAPIView,
    BeginTwoFactorEnrollmentAPIView,
    ChangePasswordAPIView,
    ConfirmTwoFactorEnrollmentAPIView,
    DeactivateUserAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeActivityAPIView,
    MeAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    PolicyAcceptanceAPIView,
    ReactivateUserAPIView,
    RegenerateTwoFactorRecoveryCodesAPIView,
    RefreshAPIView,
    RegisterAPIView,
    AuthAuditEventListAPIView,
    AuthAuditSummaryAPIView,
    SessionAPIView,
    TwoFactorRecoveryCodesAPIView,
    VerifyTwoFactorAPIView,
    VerifyProfileIdentityTwoFactorAPIView,
)

urlpatterns = [
    path("access/request/", AccessRequestAPIView.as_view(), name="access-request"),
    path("access/request/options/", AccessRequestOptionsAPIView.as_view(), name="access-request-options"),
    path("access/requests/", AccessRequestListAPIView.as_view(), name="access-request-list"),
    path("access/requests/<int:request_id>/approve/", AccessRequestApproveAPIView.as_view(), name="access-request-approve"),
    path("access/requests/<int:request_id>/reject/", AccessRequestRejectAPIView.as_view(), name="access-request-reject"),
    path("login/", LoginAPIView.as_view(), name="auth-login"),
    path("verify-2fa/", VerifyTwoFactorAPIView.as_view(), name="auth-verify-2fa"),
    path("2fa/setup/", BeginTwoFactorEnrollmentAPIView.as_view(), name="auth-2fa-setup"),
    path("2fa/setup/confirm/", ConfirmTwoFactorEnrollmentAPIView.as_view(), name="auth-2fa-setup-confirm"),
    path("2fa/recovery-codes/", TwoFactorRecoveryCodesAPIView.as_view(), name="auth-2fa-recovery-codes"),
    path(
        "2fa/recovery-codes/regenerate/",
        RegenerateTwoFactorRecoveryCodesAPIView.as_view(),
        name="auth-2fa-recovery-codes-regenerate",
    ),
    path("refresh/", RefreshAPIView.as_view(), name="auth-refresh"),
    path("session/", SessionAPIView.as_view(), name="auth-session"),
    path("policy-acceptance/", PolicyAcceptanceAPIView.as_view(), name="auth-policy-acceptance"),
    path("logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("password-reset/request/", PasswordResetRequestAPIView.as_view(), name="auth-password-reset-request"),
    path("password-reset/confirm/", PasswordResetConfirmAPIView.as_view(), name="auth-password-reset-confirm"),
    path("change-password/", ChangePasswordAPIView.as_view(), name="auth-change-password"),
    path("me/", MeAPIView.as_view(), name="auth-me"),
    path("me/identity/verify-2fa/", VerifyProfileIdentityTwoFactorAPIView.as_view(), name="auth-me-identity-verify-2fa"),
    path("me/activity/", MeActivityAPIView.as_view(), name="auth-me-activity"),
    path("register/", RegisterAPIView.as_view(), name="auth-register"),
    path("audit-events/", AuthAuditEventListAPIView.as_view(), name="auth-audit-events"),
    path("audit-events/summary/", AuthAuditSummaryAPIView.as_view(), name="auth-audit-summary"),
    path("users/<int:user_id>/deactivate/", DeactivateUserAPIView.as_view(), name="auth-user-deactivate"),
    path("users/<int:user_id>/reactivate/", ReactivateUserAPIView.as_view(), name="auth-user-reactivate"),
]
