from __future__ import annotations

import logging

from django.db import transaction
from django.utils import timezone

from risk.models import ModelRun, RiskScore, Ward

from .data import build_mock_inference_rows, build_mock_training_rows
from .model import (
    FEATURE_KEYS,
    evaluate_baseline_model,
    predict_probabilities,
    probability_to_predicted_cases,
    probability_to_risk_level,
    train_baseline_model,
)


ml_logger = logging.getLogger("risk.ml")


def run_mock_prediction_pipeline(
    *,
    month: int,
    model_version: str = "lr-v1",
    trigger_alerts: bool = False,
    send_sms: bool = False,
) -> list[RiskScore]:
    if trigger_alerts:
        from risk.tasks import trigger_alerts_task

    wards = Ward.objects.filter(is_active=True).order_by("name")
    inference_dataset = build_mock_inference_rows(wards, month=month)
    inference_rows = inference_dataset.rows
    training_rows = build_mock_training_rows()
    model = train_baseline_model(training_rows)
    evaluation_metrics = evaluate_baseline_model(model, training_rows)
    predictions = predict_probabilities(model, inference_rows)

    created_scores: list[RiskScore] = []

    ml_logger.info(
        "risk_model_run_started",
        extra={"ward_count": wards.count(), "model_version": model_version, "month": month},
    )

    with transaction.atomic():
        model_run = ModelRun.objects.create(
            algorithm_name="logistic-regression-baseline",
            model_version=model_version,
            status=ModelRun.STATUS_RUNNING,
            month=month,
            feature_schema_version="mock-v1",
            feature_keys=FEATURE_KEYS,
            training_dataset_ref="mock-training-dataset:v1",
            inference_dataset_ref=f"mock-inference-dataset:month-{month}",
            training_row_count=len(training_rows),
            inference_row_count=len(inference_rows),
            evaluation_metrics=evaluation_metrics,
            metadata={
                "trigger_alerts": trigger_alerts,
                "send_sms": send_sms,
            },
            rainfall_ingestion_run=inference_dataset.rainfall_ingestion_run,
        )
        ward_map = {ward.id: ward for ward in wards}

        for prediction in predictions:
            ward = ward_map[prediction["ward_id"]]
            probability = prediction["predicted_probability"]
            risk_level = probability_to_risk_level(probability)
            predicted_cases = probability_to_predicted_cases(probability)

            risk_score = RiskScore.objects.create(
                ward=ward,
                model_run=model_run,
                score=probability,
                risk_level=risk_level,
                rainfall_mm=prediction["rainfall_mm"],
                flood_indicator=prediction["flood_indicator"],
                predicted_cases=predicted_cases,
                source=RiskScore.SOURCE_MODEL,
                model_version=model_version,
                notes=(
                    "Generated by logistic regression baseline using rainfall input, "
                    "flood proxy, historical cases, seasonality, and population proxy."
                ),
                generated_at=timezone.now(),
            )

            ward.current_risk_level = risk_level
            ward.current_risk_score = probability
            ward.save(update_fields=["current_risk_level", "current_risk_score", "updated_at"])

            created_scores.append(risk_score)

            if trigger_alerts and risk_level == Ward.RISK_HIGH:
                trigger_alerts_task.delay(risk_score.id, send_sms=send_sms)

        model_run.status = ModelRun.STATUS_SUCCESS
        model_run.completed_at = timezone.now()
        model_run.save(update_fields=["status", "completed_at"])

    ml_logger.info(
        "risk_model_run_completed",
        extra={"scores_created": len(created_scores), "model_version": model_version, "model_run_id": model_run.id},
    )

    return created_scores
