export const CHV_SUPPORTED_LANGUAGES = ["en", "sw", "luo"] as const;

export type ChvSupportedLanguage = (typeof CHV_SUPPORTED_LANGUAGES)[number];

export const CHV_LANGUAGE_OPTIONS: Array<{ code: ChvSupportedLanguage; label: string }> = [
  { code: "en", label: "English" },
  { code: "sw", label: "Kiswahili" },
  { code: "luo", label: "Dholuo" },
];

const EN_CHV_UI_TRANSLATIONS = {
  "app.loadingWorkspace": "Loading CHV workspace",
  "app.restoringSession": "Restoring your session",
  "brand.field": "CCHIS Field",
  "page.title": "CHV follow-up",
  "language.label": "Language",
  "language.loading": "Updating",
  "language.fallback": "English fallback",
  "language.bundle": "Bundle language",
  "appearance.label": "Appearance",
  "appearance.light": "Light",
  "appearance.system": "System",
  "appearance.dark": "Dark",
  "nav.tasks": "Tasks",
  "nav.triage": "Triage",
  "nav.guidance": "Guidance",
  "nav.sync": "Sync",
  "nav.profile": "Profile",
  "nav.ariaLabel": "CHV offline views",
  "status.online": "Online",
  "status.offline": "Offline",
  "status.clear": "Clear",
  "status.sent": "Sent",
  "status.pending": "Pending",
  "status.rejected": "Rejected",
  "status.assigned": "Assigned",
  "status.stale": "Stale",
  "status.ready": "Ready",
  "status.unavailable": "Unavailable",
  "status.openCount": "{count} open",
  "status.pendingCount": "{count} pending",
  "status.rejectedCount": "{count} rejected",
  "date.notSet": "Not set",
  "task.list": "Task list",
  "task.householdFollowUp": "Household follow-up",
  "task.coverageFollowUp": "Coverage follow-up",
  "task.wardFollowUp": "Ward follow-up",
  "task.none": "No assigned tasks.",
  "task.priority": "Priority",
  "task.due": "Due",
  "task.dueAt": "Due {date}",
  "task.bundle": "Bundle",
  "task.startTriage": "Start triage",
  "task.openGuidance": "Open guidance",
  "task.fieldAction": "Field action",
  "task.fieldActionHelp": "Save task progress for the next sync.",
  "task.acknowledge": "Acknowledge",
  "task.householdsReached": "Households reached",
  "task.messagesDelivered": "Messages delivered",
  "task.waterTreatmentDemo": "Water treatment demo",
  "task.soapOrHandwashing": "Soap or handwashing",
  "task.savePreventionVisit": "Save prevention visit",
  "triage.title": "Symptom triage",
  "triage.noTask": "No task selected",
  "triage.diarrhea": "Diarrhea",
  "triage.vomiting": "Vomiting",
  "triage.dehydration": "Dehydration",
  "triage.fever": "Fever",
  "triage.shortNote": "Short note",
  "triage.optional": "Optional",
  "triage.saveFollowUp": "Save follow-up",
  "triage.clear": "Clear",
  "triage.recommendationUnavailableTitle": "Recommendation unavailable",
  "triage.recommendationUnavailableBody": "Download the offline bundle before using decision support.",
  "triage.recommendationFallback": "English recommendation shown for this item.",
  "guidance.title": "Prevention guidance",
  "guidance.fallbackItem": "English guidance shown for this item.",
  "guidance.emptyTitle": "Guidance unavailable",
  "guidance.emptyBody": "Download an approved offline guidance bundle before using field guidance.",
  "sync.title": "Pending sync queue",
  "sync.lastSync": "Last sync {date}",
  "sync.now": "Sync now",
  "sync.queuedAt": "Queued {date}",
  "sync.allSent": "All saved work is sent.",
  "sync.conflictReview": "Sync conflict review",
  "sync.noConflicts": "No conflicts.",
  "sync.dismiss": "Dismiss",
  "conflict.REPLAYED": "Duplicate sync",
  "conflict.SCOPE_MISMATCH": "Ward scope mismatch",
  "conflict.STALE_BUNDLE": "Stale bundle",
  "conflict.UNSUPPORTED_UPLOAD": "Unsupported upload",
  "conflict.NONE": "No conflict",
  "sync.countSent": "{count} sent",
  "sync.countRejected": "{count} rejected",
  "sync.countRetry": "{count} waiting to retry",
  "profile.ward": "Ward",
  "profile.device": "Device",
  "profile.localBrowser": "Local browser",
  "profile.bundle": "Bundle",
  "profile.localFallback": "Local fallback",
  "profile.expires": "Expires",
  "ward.assignedFallback": "Assigned ward",
  "ward.unassigned": "Unassigned",
  "offline.title": "Offline status",
  "offline.connection": "Connection",
  "offline.work": "Work",
  "offline.bundle": "Bundle",
  "nextAction.title": "Next action",
  "nextAction.syncPending": "Sync pending work.",
  "nextAction.keepSaved": "Keep pending work saved.",
  "nextAction.openTriage": "Open triage.",
  "nextAction.waitAssignment": "Wait for assignment.",
  "nextAction.openSync": "Open sync",
  "upload.prevention_visit": "Prevention visit",
  "upload.task_ack": "Task acknowledgement",
  "upload.alert_ack": "Alert acknowledgement",
  "upload.suspected_case_signal": "Suspected-case signal",
  "upload.symptom_triage": "Symptom triage",
  "message.selectSymptom": "Select at least one symptom before saving.",
  "message.localFallbackBundle": "Using the local fallback bundle until the live assignment bundle is available.",
  "message.followUpSaved": "Follow-up saved on this device.",
  "message.taskCannotAck": "This task cannot be acknowledged offline.",
  "message.taskAckSaved": "Task acknowledgement saved on this device.",
  "message.taskCannotPrevention": "This task cannot record a prevention visit offline.",
  "message.preventionSaved": "Prevention visit saved on this device.",
  "message.offlinePending": "Offline. Pending work will stay on this device.",
  "message.noPendingWork": "No pending work to sync.",
  "message.sent": "Sent.",
  "message.syncError": "Unable to sync offline work.",
  "message.wardRequired": "An assigned ward is required before syncing.",
  "message.languageSavedOffline": "Language saved on this device. New bundles will download when online.",
  "message.languageUpdated": "Language bundle updated.",
  "message.languageFallback": "Language saved. English guidance is shown where translated guidance is unavailable.",
} as const;

export type ChvUiTranslationKey = keyof typeof EN_CHV_UI_TRANSLATIONS;

const SW_CHV_UI_TRANSLATIONS: Record<ChvUiTranslationKey, string> = {
  "app.loadingWorkspace": "Inapakia nafasi ya kazi ya CHV",
  "app.restoringSession": "Inarejesha kikao chako",
  "brand.field": "CCHIS Shambani",
  "page.title": "Ufuatiliaji wa CHV",
  "language.label": "Lugha",
  "language.loading": "Inasasisha",
  "language.fallback": "Imerejea Kiingereza",
  "language.bundle": "Lugha ya kifurushi",
  "appearance.label": "Mwonekano",
  "appearance.light": "Mwanga",
  "appearance.system": "Mfumo",
  "appearance.dark": "Giza",
  "nav.tasks": "Kazi",
  "nav.triage": "Uchunguzi",
  "nav.guidance": "Mwongozo",
  "nav.sync": "Sawazisha",
  "nav.profile": "Wasifu",
  "nav.ariaLabel": "Mitazamo ya CHV nje ya mtandao",
  "status.online": "Mtandaoni",
  "status.offline": "Nje ya mtandao",
  "status.clear": "Safi",
  "status.sent": "Imetumwa",
  "status.pending": "Inasubiri",
  "status.rejected": "Imekataliwa",
  "status.assigned": "Imepangiwa",
  "status.stale": "Imezeeka",
  "status.ready": "Tayari",
  "status.unavailable": "Haipatikani",
  "status.openCount": "{count} wazi",
  "status.pendingCount": "{count} zinasubiri",
  "status.rejectedCount": "{count} zimekataliwa",
  "date.notSet": "Haijawekwa",
  "task.list": "Orodha ya kazi",
  "task.householdFollowUp": "Ufuatiliaji wa kaya",
  "task.coverageFollowUp": "Ufuatiliaji wa eneo",
  "task.wardFollowUp": "Ufuatiliaji wa wadi",
  "task.none": "Hakuna kazi ulizopewa.",
  "task.priority": "Kipaumbele",
  "task.due": "Muda",
  "task.dueAt": "Muda {date}",
  "task.bundle": "Kifurushi",
  "task.startTriage": "Anza uchunguzi",
  "task.openGuidance": "Fungua mwongozo",
  "task.fieldAction": "Hatua ya shambani",
  "task.fieldActionHelp": "Hifadhi maendeleo ya kazi kwa usawazishaji unaofuata.",
  "task.acknowledge": "Thibitisha",
  "task.householdsReached": "Kaya zilizofikiwa",
  "task.messagesDelivered": "Ujumbe uliotolewa",
  "task.waterTreatmentDemo": "Onyesho la kutibu maji",
  "task.soapOrHandwashing": "Sabuni au kunawa mikono",
  "task.savePreventionVisit": "Hifadhi ziara ya kinga",
  "triage.title": "Uchunguzi wa dalili",
  "triage.noTask": "Hakuna kazi iliyochaguliwa",
  "triage.diarrhea": "Kuharisha",
  "triage.vomiting": "Kutapika",
  "triage.dehydration": "Upungufu wa maji mwilini",
  "triage.fever": "Homa",
  "triage.shortNote": "Dokezo fupi",
  "triage.optional": "Si lazima",
  "triage.saveFollowUp": "Hifadhi ufuatiliaji",
  "triage.clear": "Futa",
  "triage.recommendationUnavailableTitle": "Pendekezo halipatikani",
  "triage.recommendationUnavailableBody": "Pakua kifurushi cha nje ya mtandao kabla ya kutumia msaada wa maamuzi.",
  "triage.recommendationFallback": "Pendekezo la Kiingereza linaonyeshwa kwa kipengee hiki.",
  "guidance.title": "Mwongozo wa kinga",
  "guidance.fallbackItem": "Mwongozo wa Kiingereza unaonyeshwa kwa kipengee hiki.",
  "guidance.emptyTitle": "Mwongozo haupatikani",
  "guidance.emptyBody": "Pakua kifurushi cha mwongozo kilichoidhinishwa kabla ya kutumia mwongozo wa shambani.",
  "sync.title": "Foleni ya kusawazisha",
  "sync.lastSync": "Usawazishaji wa mwisho {date}",
  "sync.now": "Sawazisha sasa",
  "sync.queuedAt": "Iliwekwa {date}",
  "sync.allSent": "Kazi yote iliyohifadhiwa imetumwa.",
  "sync.conflictReview": "Mapitio ya migongano ya usawazishaji",
  "sync.noConflicts": "Hakuna migongano.",
  "sync.dismiss": "Ondoa",
  "conflict.REPLAYED": "Usawazishaji uliorudiwa",
  "conflict.SCOPE_MISMATCH": "Wadi haitalingana na ruhusa",
  "conflict.STALE_BUNDLE": "Kifurushi kimezeeka",
  "conflict.UNSUPPORTED_UPLOAD": "Upakiaji haukubaliwi",
  "conflict.NONE": "Hakuna mgongano",
  "sync.countSent": "{count} zimetumwa",
  "sync.countRejected": "{count} zimekataliwa",
  "sync.countRetry": "{count} zinasubiri jaribio tena",
  "profile.ward": "Wadi",
  "profile.device": "Kifaa",
  "profile.localBrowser": "Kivinjari cha hapa",
  "profile.bundle": "Kifurushi",
  "profile.localFallback": "Kifurushi cha hapa",
  "profile.expires": "Muda wa mwisho",
  "ward.assignedFallback": "Wadi uliyopewa",
  "ward.unassigned": "Hujapangiwa",
  "offline.title": "Hali ya nje ya mtandao",
  "offline.connection": "Muunganisho",
  "offline.work": "Kazi",
  "offline.bundle": "Kifurushi",
  "nextAction.title": "Hatua inayofuata",
  "nextAction.syncPending": "Sawazisha kazi zinazosubiri.",
  "nextAction.keepSaved": "Weka kazi zinazosubiri kwenye kifaa.",
  "nextAction.openTriage": "Fungua uchunguzi.",
  "nextAction.waitAssignment": "Subiri kazi.",
  "nextAction.openSync": "Fungua usawazishaji",
  "upload.prevention_visit": "Ziara ya kinga",
  "upload.task_ack": "Uthibitisho wa kazi",
  "upload.alert_ack": "Uthibitisho wa tahadhari",
  "upload.suspected_case_signal": "Ishara ya kesi inayoshukiwa",
  "upload.symptom_triage": "Uchunguzi wa dalili",
  "message.selectSymptom": "Chagua angalau dalili moja kabla ya kuhifadhi.",
  "message.localFallbackBundle": "Inatumia kifurushi cha hapa hadi kifurushi halisi kipatikane.",
  "message.followUpSaved": "Ufuatiliaji umehifadhiwa kwenye kifaa hiki.",
  "message.taskCannotAck": "Kazi hii haiwezi kuthibitishwa nje ya mtandao.",
  "message.taskAckSaved": "Uthibitisho wa kazi umehifadhiwa kwenye kifaa hiki.",
  "message.taskCannotPrevention": "Kazi hii haiwezi kurekodi ziara ya kinga nje ya mtandao.",
  "message.preventionSaved": "Ziara ya kinga imehifadhiwa kwenye kifaa hiki.",
  "message.offlinePending": "Uko nje ya mtandao. Kazi zitasalia kwenye kifaa hiki.",
  "message.noPendingWork": "Hakuna kazi inayosubiri kusawazishwa.",
  "message.sent": "Imetumwa.",
  "message.syncError": "Imeshindikana kusawazisha kazi za nje ya mtandao.",
  "message.wardRequired": "Wadi uliyopewa inahitajika kabla ya kusawazisha.",
  "message.languageSavedOffline": "Lugha imehifadhiwa kwenye kifaa hiki. Vifurushi vipya vitapakuliwa ukiwa mtandaoni.",
  "message.languageUpdated": "Kifurushi cha lugha kimesasishwa.",
  "message.languageFallback": "Lugha imehifadhiwa. Mwongozo wa Kiingereza unaonekana pale tafsiri haipatikani.",
};

const LUO_CHV_UI_TRANSLATIONS: Record<ChvUiTranslationKey, string> = {
  "app.loadingWorkspace": "Tiyo mar CHV tye kachako",
  "app.restoringSession": "Dweltini duogo",
  "brand.field": "CCHIS e pap",
  "page.title": "Luwo wach CHV",
  "language.label": "Dho",
  "language.loading": "Tye ka keto manyien",
  "language.fallback": "Oduogo e English",
  "language.bundle": "Dho mar bundle",
  "appearance.label": "Kido",
  "appearance.light": "Ler",
  "appearance.system": "System",
  "appearance.dark": "Mudho",
  "nav.tasks": "Tije",
  "nav.triage": "Yiero tuo",
  "nav.guidance": "Puonj",
  "nav.sync": "Riwre",
  "nav.profile": "Profil",
  "nav.ariaLabel": "Neno tije CHV ma ok e intanet",
  "status.online": "E intanet",
  "status.offline": "Ok e intanet",
  "status.clear": "Ber",
  "status.sent": "Osend",
  "status.pending": "Orwako",
  "status.rejected": "Okwedo",
  "status.assigned": "Omiyi",
  "status.stale": "Oti",
  "status.ready": "Oyikore",
  "status.unavailable": "Ok oyudre",
  "status.openCount": "{count} oyawore",
  "status.pendingCount": "{count} orwako",
  "status.rejectedCount": "{count} okwedo",
  "date.notSet": "Ok oketi",
  "task.list": "Ranyisi mar tije",
  "task.householdFollowUp": "Luwo wach ot",
  "task.coverageFollowUp": "Luwo wach gweng",
  "task.wardFollowUp": "Luwo wach ward",
  "task.none": "Onge tich ma omiyi.",
  "task.priority": "Ber moloyo",
  "task.due": "Kare",
  "task.dueAt": "Kare {date}",
  "task.bundle": "Bundle",
  "task.startTriage": "Chak yiero tuo",
  "task.openGuidance": "Yab puonj",
  "task.fieldAction": "Tich e pap",
  "task.fieldActionHelp": "Kan tich mondo oriwre bang'e.",
  "task.acknowledge": "Yie",
  "task.householdsReached": "Ote ma ochopo",
  "task.messagesDelivered": "Wach ma okelo",
  "task.waterTreatmentDemo": "Nyiso kaka pi ithiedho",
  "task.soapOrHandwashing": "Sabun kata luoko lwet",
  "task.savePreventionVisit": "Kan limo mar geng'o",
  "triage.title": "Yiero ranyisi tuo",
  "triage.noTask": "Onge tich ma oyiero",
  "triage.diarrhea": "Lweyo",
  "triage.vomiting": "Nindo",
  "triage.dehydration": "Remo pi e ringruok",
  "triage.fever": "Liet",
  "triage.shortNote": "Wach machuok",
  "triage.optional": "Ok nyaka",
  "triage.saveFollowUp": "Kan luwo wach",
  "triage.clear": "Gol",
  "triage.recommendationUnavailableTitle": "Puonj ok oyudre",
  "triage.recommendationUnavailableBody": "Lor bundle mar ok e intanet kapok itiyo gi kony mar paro.",
  "triage.recommendationFallback": "Puonj mar English ema nyiso e kany.",
  "guidance.title": "Puonj mar geng'o",
  "guidance.fallbackItem": "Puonj mar English ema nyiso e kany.",
  "guidance.emptyTitle": "Puonj ok oyudre",
  "guidance.emptyBody": "Lor bundle mar puonj moyie kapok itiyo gi puonj mar puodho.",
  "sync.title": "Tije ma orwako riwre",
  "sync.lastSync": "Riwruok mogik {date}",
  "sync.now": "Riw sani",
  "sync.queuedAt": "Oketo {date}",
  "sync.allSent": "Tije duto mokan osend.",
  "sync.conflictReview": "Nonro mar chandruok riwre",
  "sync.noConflicts": "Onge chandruok.",
  "sync.dismiss": "Geng'",
  "conflict.REPLAYED": "Riwruok odok kendo",
  "conflict.SCOPE_MISMATCH": "Ward ok rwate",
  "conflict.STALE_BUNDLE": "Bundle oti",
  "conflict.UNSUPPORTED_UPLOAD": "Upload ok oyie",
  "conflict.NONE": "Onge chandruok",
  "sync.countSent": "{count} osend",
  "sync.countRejected": "{count} okwedo",
  "sync.countRetry": "{count} orwako tem kendo",
  "profile.ward": "Ward",
  "profile.device": "Kifaa",
  "profile.localBrowser": "Browser mar kany",
  "profile.bundle": "Bundle",
  "profile.localFallback": "Bundle mar kany",
  "profile.expires": "Gik kare",
  "ward.assignedFallback": "Ward ma omiyi",
  "ward.unassigned": "Pok omiyi",
  "offline.title": "Kido mar ok e intanet",
  "offline.connection": "Riwruok",
  "offline.work": "Tich",
  "offline.bundle": "Bundle",
  "nextAction.title": "Tich malubo",
  "nextAction.syncPending": "Riw tije ma orwako.",
  "nextAction.keepSaved": "Kan tije ma orwako e kifaa.",
  "nextAction.openTriage": "Yab yiero tuo.",
  "nextAction.waitAssignment": "Rit tich.",
  "nextAction.openSync": "Yab riwruok",
  "upload.prevention_visit": "Limo mar geng'o",
  "upload.task_ack": "Yie tich",
  "upload.alert_ack": "Yie wach mar siem",
  "upload.suspected_case_signal": "Ranyisi mar case ma dwaro nono",
  "upload.symptom_triage": "Yiero ranyisi tuo",
  "message.selectSymptom": "Yier ranyisi achiel kata moloyo kapok ikan.",
  "message.localFallbackBundle": "Tiyo gi bundle mar kany nyaka bundle manyien oyudre.",
  "message.followUpSaved": "Luwo wach osekan e kifaa ni.",
  "message.taskCannotAck": "Tich ni ok nyal yie kane ok in e intanet.",
  "message.taskAckSaved": "Yie tich osekan e kifaa ni.",
  "message.taskCannotPrevention": "Tich ni ok nyal ndiko limo mar geng'o kane ok in e intanet.",
  "message.preventionSaved": "Limo mar geng'o osekan e kifaa ni.",
  "message.offlinePending": "Ok in e intanet. Tije ma orwako biro dong' e kifaa ni.",
  "message.noPendingWork": "Onge tich ma orwako riwre.",
  "message.sent": "Osend.",
  "message.syncError": "Riwruok mar tije ma ok e intanet orem.",
  "message.wardRequired": "Ward ma omiyi dwarore kapok iriwo.",
  "message.languageSavedOffline": "Dho osekan e kifaa ni. Bundle manyien biro lor kane in e intanet.",
  "message.languageUpdated": "Bundle mar dho oseket manyien.",
  "message.languageFallback": "Dho osekan. Puonj mar English nyisore ka onge lok dho.",
};

export const CHV_UI_TRANSLATIONS: Record<ChvSupportedLanguage, Record<ChvUiTranslationKey, string>> = {
  en: EN_CHV_UI_TRANSLATIONS,
  sw: SW_CHV_UI_TRANSLATIONS,
  luo: LUO_CHV_UI_TRANSLATIONS,
};

export function normalizeChvLanguage(value: string | null | undefined): ChvSupportedLanguage {
  const normalized = (value ?? "").trim().toLowerCase();
  return CHV_SUPPORTED_LANGUAGES.includes(normalized as ChvSupportedLanguage)
    ? (normalized as ChvSupportedLanguage)
    : "en";
}

export function chvTranslate(
  language: string | null | undefined,
  key: ChvUiTranslationKey,
  values: Record<string, string | number> = {},
) {
  const dictionary = CHV_UI_TRANSLATIONS[normalizeChvLanguage(language)] ?? CHV_UI_TRANSLATIONS.en;
  const template = dictionary[key] ?? CHV_UI_TRANSLATIONS.en[key] ?? key;
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
